// js/items.js — equippable item catalog (see js/equipment.js for the item schema)

export const ITEMS = {
  bag1: {
    id:     'bag1',
    name:   'Bag',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag1.png',
  },
  bag2: {
    id:     'bag2',
    name:   'Bag II',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag2.png',
  },
  bag3: {
    id:     'bag3',
    name:   'Bag III',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag3.png',
  },
  bag4: {
    id:     'bag4',
    name:   'Bag IV',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag4.png',
  },
  bag5: {
    id:     'bag5',
    name:   'Bag V',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag5.png',
  },
  bag6: {
    id:     'bag6',
    name:   'Bag VI',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag6.png',
  },
  bag7: {
    id:     'bag7',
    name:   'Bag VII',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag7.png',
  },
  bag8: {
    id:     'bag8',
    name:   'Bag VIII',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag8.png',
  },
  bag9: {
    id:     'bag9',
    name:   'Bag IX',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag9.png',
  },
  bag10: {
    id:     'bag10',
    name:   'Bag X',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag10.png',
  },
  bag11: {
    id:     'bag11',
    name:   'Bag XI',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag11.png',
  },

  handaxe: {
    id:     'handaxe',
    name:   'Handaxe',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/handaxe.png',
    dmg:    '1d6',
    dmgType: 'slashing',
    light:  true,
    thrown: true,
  },
  battleaxe: {
    id:     'battleaxe',
    name:   'Battleaxe',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/battleaxe.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
  },
  greataxe: {
    id:     'greataxe',
    name:   'Greataxe',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/greataxe.png',
    dmg:    '1d12',
    dmgType: 'slashing',
    heavy:  true,
    twoHanded: true,
  },

  warhammer1: {
    id:     'warhammer1',
    name:   'Warhammer',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer1.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
  },
  warhammer2: {
    id:     'warhammer2',
    name:   'Warhammer II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer2.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
  },
  warhammer3: {
    id:     'warhammer3',
    name:   'Warhammer III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer3.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
  },
  warhammer4: {
    id:     'warhammer4',
    name:   'Warhammer IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer4.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
  },
  warhammer5: {
    id:     'warhammer5',
    name:   'Warhammer V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer5.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
  },
  warhammer6: {
    id:     'warhammer6',
    name:   'Warhammer VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer6.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
  },
  warhammer7: {
    id:     'warhammer7',
    name:   'Warhammer VII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer7.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
  },
  warhammer8: {
    id:     'warhammer8',
    name:   'Warhammer VIII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer8.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
  },
  warhammer9: {
    id:     'warhammer9',
    name:   'Warhammer IX',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer9.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
  },
  warhammer10: {
    id:     'warhammer10',
    name:   'Warhammer X',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer10.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
  },

  sword1: {
    id:     'sword1',
    name:   'Longsword',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword1.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
  },
  sword2: {
    id:     'sword2',
    name:   'Longsword II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword2.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
  },
  sword3: {
    id:     'sword3',
    name:   'Longsword III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword3.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
  },
  sword4: {
    id:     'sword4',
    name:   'Longsword IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword4.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
  },
  sword5: {
    id:     'sword5',
    name:   'Longsword V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword5.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
  },
  sword6: {
    id:     'sword6',
    name:   'Longsword VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword6.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
  },
  sword7: {
    id:     'sword7',
    name:   'Longsword VII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword7.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
  },
  sword8: {
    id:     'sword8',
    name:   'Longsword VIII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword8.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
  },

  stave1: {
    id:     'stave1',
    name:   'Quarterstaff',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave1.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
  },
  stave2: {
    id:     'stave2',
    name:   'Quarterstaff II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave2.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
  },
  stave3: {
    id:     'stave3',
    name:   'Quarterstaff III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave3.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
  },
  stave4: {
    id:     'stave4',
    name:   'Quarterstaff IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave4.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
  },
  stave5: {
    id:     'stave5',
    name:   'Quarterstaff V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave5.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
  },
  stave6: {
    id:     'stave6',
    name:   'Quarterstaff VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave6.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
  },
  stave7: {
    id:     'stave7',
    name:   'Quarterstaff VII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave7.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
  },
  stave8: {
    id:     'stave8',
    name:   'Quarterstaff VIII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave8.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
  },

  wand1: {
    id:     'wand1',
    name:   'Wand',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand1.png',
  },
  wand2: {
    id:     'wand2',
    name:   'Wand II',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand2.png',
  },
  wand3: {
    id:     'wand3',
    name:   'Wand III',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand3.png',
  },
  wand4: {
    id:     'wand4',
    name:   'Wand IV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand4.png',
  },
  wand5: {
    id:     'wand5',
    name:   'Wand V',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand5.png',
  },
  wand6: {
    id:     'wand6',
    name:   'Wand VI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand6.png',
  },
  wand7: {
    id:     'wand7',
    name:   'Wand VII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand7.png',
  },
  wand8: {
    id:     'wand8',
    name:   'Wand VIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand8.png',
  },
  wand9: {
    id:     'wand9',
    name:   'Wand IX',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand9.png',
  },
  wand10: {
    id:     'wand10',
    name:   'Wand X',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand10.png',
  },
  wand11: {
    id:     'wand11',
    name:   'Wand XI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand11.png',
  },
  wand12: {
    id:     'wand12',
    name:   'Wand XII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand12.png',
  },

  orb1: {
    id:     'orb1',
    name:   'Orb',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb1.png',
  },
  orb2: {
    id:     'orb2',
    name:   'Orb II',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb2.png',
  },
  orb3: {
    id:     'orb3',
    name:   'Orb III',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb3.png',
  },
  orb4: {
    id:     'orb4',
    name:   'Orb IV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb4.png',
  },
  orb5: {
    id:     'orb5',
    name:   'Orb V',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb5.png',
  },
  orb6: {
    id:     'orb6',
    name:   'Orb VI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb6.png',
  },
  orb7: {
    id:     'orb7',
    name:   'Orb VII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb7.png',
  },
  orb8: {
    id:     'orb8',
    name:   'Orb VIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb8.png',
  },
  orb9: {
    id:     'orb9',
    name:   'Orb IX',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb9.png',
  },
  orb10: {
    id:     'orb10',
    name:   'Orb X',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb10.png',
  },
  orb11: {
    id:     'orb11',
    name:   'Orb XI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb11.png',
  },
  orb12: {
    id:     'orb12',
    name:   'Orb XII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb12.png',
  },
  orb13: {
    id:     'orb13',
    name:   'Orb XIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb13.png',
  },
  orb14: {
    id:     'orb14',
    name:   'Orb XIV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb14.png',
  },
  orb15: {
    id:     'orb15',
    name:   'Orb XV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb15.png',
  },

  shield1: {
    id:     'shield1',
    name:   'Shield',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield1.png',
    ac:     2,
  },
  shield2: {
    id:     'shield2',
    name:   'Shield II',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield2.png',
    ac:     2,
  },
  shield3: {
    id:     'shield3',
    name:   'Shield III',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield3.png',
    ac:     2,
  },
  shield4: {
    id:     'shield4',
    name:   'Shield IV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield4.png',
    ac:     2,
  },
  shield5: {
    id:     'shield5',
    name:   'Shield V',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield5.png',
    ac:     2,
  },
  shield6: {
    id:     'shield6',
    name:   'Shield VI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield6.png',
    ac:     2,
  },
  shield7: {
    id:     'shield7',
    name:   'Shield VII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield7.png',
    ac:     2,
  },
  shield8: {
    id:     'shield8',
    name:   'Shield VIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield8.png',
    ac:     2,
  },
  shield9: {
    id:     'shield9',
    name:   'Shield IX',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield9.png',
    ac:     2,
  },
  shield10: {
    id:     'shield10',
    name:   'Shield X',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield10.png',
    ac:     2,
  },
  shield11: {
    id:     'shield11',
    name:   'Shield XI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield11.png',
    ac:     2,
  },
  shield12: {
    id:     'shield12',
    name:   'Shield XII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield12.png',
    ac:     2,
  },
  shield13: {
    id:     'shield13',
    name:   'Shield XIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield13.png',
    ac:     2,
  },
  shield14: {
    id:     'shield14',
    name:   'Shield XIV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield14.png',
    ac:     2,
  },
  shield15: {
    id:     'shield15',
    name:   'Shield XV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield15.png',
    ac:     2,
  },

  dagger1: {
    id:     'dagger1',
    name:   'Dagger',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger1.png',
    dmg:    '1d4',
    dmgType: 'piercing',
    finesse: true,
    light:   true,
    thrown:  true,
  },
  dagger2: {
    id:     'dagger2',
    name:   'Dagger II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger2.png',
    dmg:    '1d4',
    dmgType: 'piercing',
    finesse: true,
    light:   true,
    thrown:  true,
  },
  dagger3: {
    id:     'dagger3',
    name:   'Dagger III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger3.png',
    dmg:    '1d4',
    dmgType: 'piercing',
    finesse: true,
    light:   true,
    thrown:  true,
  },
  dagger4: {
    id:     'dagger4',
    name:   'Dagger IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger4.png',
    dmg:    '1d4',
    dmgType: 'piercing',
    finesse: true,
    light:   true,
    thrown:  true,
  },
  dagger5: {
    id:     'dagger5',
    name:   'Dagger V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger5.png',
    dmg:    '1d4',
    dmgType: 'piercing',
    finesse: true,
    light:   true,
    thrown:  true,
  },
  dagger6: {
    id:     'dagger6',
    name:   'Dagger VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger6.png',
    dmg:    '1d4',
    dmgType: 'piercing',
    finesse: true,
    light:   true,
    thrown:  true,
  },

  longbow1: {
    id:     'longbow1',
    name:   'Longbow',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/longbow1.png',
    dmg:    '1d8',
    dmgType: 'piercing',
    heavy:  true,
    twoHanded: true,
    ammunition: true,
  },
  longbow2: {
    id:     'longbow2',
    name:   'Longbow II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/longbow2.png',
    dmg:    '1d8',
    dmgType: 'piercing',
    heavy:  true,
    twoHanded: true,
    ammunition: true,
  },
  longbow3: {
    id:     'longbow3',
    name:   'Longbow III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/longbow3.png',
    dmg:    '1d8',
    dmgType: 'piercing',
    heavy:  true,
    twoHanded: true,
    ammunition: true,
  },
  longbow4: {
    id:     'longbow4',
    name:   'Longbow IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/longbow4.png',
    dmg:    '1d8',
    dmgType: 'piercing',
    heavy:  true,
    twoHanded: true,
    ammunition: true,
  },
  longbow5: {
    id:     'longbow5',
    name:   'Longbow V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/longbow5.png',
    dmg:    '1d8',
    dmgType: 'piercing',
    heavy:  true,
    twoHanded: true,
    ammunition: true,
  },
  longbow6: {
    id:     'longbow6',
    name:   'Longbow VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/longbow6.png',
    dmg:    '1d8',
    dmgType: 'piercing',
    heavy:  true,
    twoHanded: true,
    ammunition: true,
  },

  crossbow1: {
    id:     'crossbow1',
    name:   'Heavy Crossbow',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/crossbow1.png',
    dmg:    '1d10',
    dmgType: 'piercing',
    heavy:  true,
    twoHanded: true,
    ammunition: true,
    loading: true,
  },
  crossbow2: {
    id:     'crossbow2',
    name:   'Heavy Crossbow II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/crossbow2.png',
    dmg:    '1d10',
    dmgType: 'piercing',
    heavy:  true,
    twoHanded: true,
    ammunition: true,
    loading: true,
  },
  crossbow3: {
    id:     'crossbow3',
    name:   'Light Crossbow',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/crossbow3.png',
    dmg:    '1d8',
    dmgType: 'piercing',
    twoHanded: true,
    ammunition: true,
    loading: true,
  },
  crossbow4: {
    id:     'crossbow4',
    name:   'Heavy Crossbow IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/crossbow4.png',
    dmg:    '1d10',
    dmgType: 'piercing',
    heavy:  true,
    twoHanded: true,
    ammunition: true,
    loading: true,
  },
  crossbow5: {
    id:     'crossbow5',
    name:   'Heavy Crossbow V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/crossbow5.png',
    dmg:    '1d10',
    dmgType: 'piercing',
    heavy:  true,
    twoHanded: true,
    ammunition: true,
    loading: true,
  },
  crossbow6: {
    id:     'crossbow6',
    name:   'Heavy Crossbow VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/crossbow6.png',
    dmg:    '1d10',
    dmgType: 'piercing',
    heavy:  true,
    twoHanded: true,
    ammunition: true,
    loading: true,
  },

  javelin1: {
    id:     'javelin1',
    name:   'Javelin',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/javelin1.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    thrown: true,
  },
  javelin2: {
    id:     'javelin2',
    name:   'Javelin II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/javelin2.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    thrown: true,
  },
  javelin3: {
    id:     'javelin3',
    name:   'Javelin III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/javelin3.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    thrown: true,
  },
  javelin4: {
    id:     'javelin4',
    name:   'Javelin IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/javelin4.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    thrown: true,
  },
  javelin5: {
    id:     'javelin5',
    name:   'Javelin V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/javelin5.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    thrown: true,
  },

  leatherarmor1: {
    id:     'leatherarmor1',
    name:   'Leather Armor',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor1.png',
    ac:     11,
  },
  leatherarmor2: {
    id:     'leatherarmor2',
    name:   'Leather Armor II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor2.png',
    ac:     11,
  },
  leatherarmor3: {
    id:     'leatherarmor3',
    name:   'Leather Armor III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor3.png',
    ac:     11,
  },
  leatherarmor4: {
    id:     'leatherarmor4',
    name:   'Leather Armor IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor4.png',
    ac:     11,
  },
  leatherarmor5: {
    id:     'leatherarmor5',
    name:   'Leather Armor V',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor5.png',
    ac:     11,
  },
  leatherarmor6: {
    id:     'leatherarmor6',
    name:   'Leather Armor VI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor6.png',
    ac:     11,
  },
  leatherarmor7: {
    id:     'leatherarmor7',
    name:   'Leather Armor VII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor7.png',
    ac:     11,
  },
  leatherarmor8: {
    id:     'leatherarmor8',
    name:   'Leather Armor VIII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor8.png',
    ac:     11,
  },
  leatherarmor9: {
    id:     'leatherarmor9',
    name:   'Leather Armor IX',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor9.png',
    ac:     11,
  },
  leatherarmor10: {
    id:     'leatherarmor10',
    name:   'Leather Armor X',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor10.png',
    ac:     11,
  },
  leatherarmor11: {
    id:     'leatherarmor11',
    name:   'Leather Armor XI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor11.png',
    ac:     11,
  },
  leatherarmor12: {
    id:     'leatherarmor12',
    name:   'Leather Armor XII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor12.png',
    ac:     11,
  },
  leatherarmor13: {
    id:     'leatherarmor13',
    name:   'Leather Armor XIII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor13.png',
    ac:     11,
  },
  leatherarmor14: {
    id:     'leatherarmor14',
    name:   'Leather Armor XIV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor14.png',
    ac:     11,
  },
  leatherarmor15: {
    id:     'leatherarmor15',
    name:   'Leather Armor XV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor15.png',
    ac:     11,
  },
  leatherarmor16: {
    id:     'leatherarmor16',
    name:   'Leather Armor XVI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor16.png',
    ac:     11,
  },

  hidearmor1: {
    id:     'hidearmor1',
    name:   'Hide Armor',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/hidearmor1.png',
    ac:     12,
  },
  hidearmor2: {
    id:     'hidearmor2',
    name:   'Hide Armor II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/hidearmor2.png',
    ac:     12,
  },
  hidearmor3: {
    id:     'hidearmor3',
    name:   'Hide Armor III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/hidearmor3.png',
    ac:     12,
  },
  hidearmor4: {
    id:     'hidearmor4',
    name:   'Hide Armor IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/hidearmor4.png',
    ac:     12,
  },
  bronzearmor: {
    id:     'bronzearmor',
    name:   'Breastplate',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/bronzearmor.png',
    ac:     14,
  },
  chainarmor1: {
    id:     'chainarmor1',
    name:   'Chain Mail',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/chainarmor1.png',
    ac:     16,
    heavy:  true,
  },
  chainarmor2: {
    id:     'chainarmor2',
    name:   'Chain Mail II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/chainarmor2.png',
    ac:     16,
    heavy:  true,
  },
  chainarmor3: {
    id:     'chainarmor3',
    name:   'Chain Mail III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/chainarmor3.png',
    ac:     16,
    heavy:  true,
  },

  platearmor1: {
    id:     'platearmor1',
    name:   'Plate Armor',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/platearmor1.png',
    ac:     18,
    heavy:  true,
  },
  platearmor2: {
    id:     'platearmor2',
    name:   'Plate Armor II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/platearmor2.png',
    ac:     18,
    heavy:  true,
  },
  platearmor3: {
    id:     'platearmor3',
    name:   'Plate Armor III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/platearmor3.png',
    ac:     18,
    heavy:  true,
  },

  leatherlegs1: {
    id:     'leatherlegs1',
    name:   'Leather Leggings',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs1.png',
    ac:     1,
  },
  leatherlegs2: {
    id:     'leatherlegs2',
    name:   'Leather Leggings II',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs2.png',
    ac:     1,
  },
  leatherlegs3: {
    id:     'leatherlegs3',
    name:   'Leather Leggings III',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs3.png',
    ac:     1,
  },
  leatherlegs4: {
    id:     'leatherlegs4',
    name:   'Leather Leggings IV',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs4.png',
    ac:     1,
  },
  leatherlegs5: {
    id:     'leatherlegs5',
    name:   'Leather Leggings V',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs5.png',
    ac:     1,
  },
  leatherlegs6: {
    id:     'leatherlegs6',
    name:   'Leather Leggings VI',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs6.png',
    ac:     1,
  },
  mixedlegs1: {
    id:     'mixedlegs1',
    name:   'Mixed Leggings',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedlegs1.png',
    ac:     2,
  },
  mixedlegs2: {
    id:     'mixedlegs2',
    name:   'Mixed Leggings II',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedlegs2.png',
    ac:     2,
  },
  mixedlegs3: {
    id:     'mixedlegs3',
    name:   'Mixed Leggings III',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedlegs3.png',
    ac:     2,
  },
  platelegs1: {
    id:     'platelegs1',
    name:   'Plate Greaves',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/platelegs1.png',
    ac:     3,
  },
  platelegs2: {
    id:     'platelegs2',
    name:   'Plate Greaves II',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/platelegs2.png',
    ac:     3,
  },
  platelegs3: {
    id:     'platelegs3',
    name:   'Plate Greaves III',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/platelegs3.png',
    ac:     3,
  },
  platelegs4: {
    id:     'platelegs4',
    name:   'Plate Greaves IV',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/platelegs4.png',
    ac:     3,
  },

  clothlegs1: {
    id:     'clothlegs1',
    name:   'Cloth Trousers',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs1.png',
  },
  clothlegs2: {
    id:     'clothlegs2',
    name:   'Cloth Trousers II',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs2.png',
  },
  clothlegs3: {
    id:     'clothlegs3',
    name:   'Cloth Trousers III',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs3.png',
  },
  clothlegs4: {
    id:     'clothlegs4',
    name:   'Cloth Trousers IV',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs4.png',
  },
  clothlegs5: {
    id:     'clothlegs5',
    name:   'Cloth Trousers V',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs5.png',
  },
  clothlegs6: {
    id:     'clothlegs6',
    name:   'Cloth Trousers VI',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs6.png',
  },
  clothlegs7: {
    id:     'clothlegs7',
    name:   'Cloth Trousers VII',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs7.png',
  },
  clothlegs8: {
    id:     'clothlegs8',
    name:   'Cloth Trousers VIII',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs8.png',
  },
  clothlegs9: {
    id:     'clothlegs9',
    name:   'Cloth Trousers IX',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs9.png',
  },
  clothlegs10: {
    id:     'clothlegs10',
    name:   'Cloth Trousers X',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs10.png',
  },
  clothlegs11: {
    id:     'clothlegs11',
    name:   'Cloth Trousers XI',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs11.png',
  },

  leatherhelm1: {
    id:     'leatherhelm1',
    name:   'Leather Helm',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm1.png',
  },
  leatherhelm2: {
    id:     'leatherhelm2',
    name:   'Leather Helm II',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm2.png',
  },
  leatherhelm3: {
    id:     'leatherhelm3',
    name:   'Leather Helm III',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm3.png',
  },
  leatherhelm4: {
    id:     'leatherhelm4',
    name:   'Leather Helm IV',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm4.png',
  },
  leatherhelm5: {
    id:     'leatherhelm5',
    name:   'Leather Helm V',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm5.png',
  },
  leatherhelm6: {
    id:     'leatherhelm6',
    name:   'Leather Helm VI',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm6.png',
  },
  leatherhelm7: {
    id:     'leatherhelm7',
    name:   'Leather Helm VII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm7.png',
  },
  leatherhelm8: {
    id:     'leatherhelm8',
    name:   'Leather Helm VIII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm8.png',
  },
  leatherhelm9: {
    id:     'leatherhelm9',
    name:   'Leather Helm IX',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm9.png',
  },

  platehelm1: {
    id:     'platehelm1',
    name:   'Plate Helm',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm1.png',
  },
  platehelm2: {
    id:     'platehelm2',
    name:   'Plate Helm II',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm2.png',
  },
  platehelm3: {
    id:     'platehelm3',
    name:   'Plate Helm III',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm3.png',
  },
  platehelm4: {
    id:     'platehelm4',
    name:   'Plate Helm IV',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm4.png',
  },
  platehelm5: {
    id:     'platehelm5',
    name:   'Plate Helm V',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm5.png',
  },
  platehelm6: {
    id:     'platehelm6',
    name:   'Plate Helm VI',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm6.png',
  },
  platehelm7: {
    id:     'platehelm7',
    name:   'Plate Helm VII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm7.png',
  },
  platehelm8: {
    id:     'platehelm8',
    name:   'Plate Helm VIII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm8.png',
  },
  platehelm9: {
    id:     'platehelm9',
    name:   'Plate Helm IX',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm9.png',
  },
  platehelm10: {
    id:     'platehelm10',
    name:   'Plate Helm X',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm10.png',
  },
  platehelm11: {
    id:     'platehelm11',
    name:   'Plate Helm XI',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm11.png',
  },
  platehelm12: {
    id:     'platehelm12',
    name:   'Plate Helm XII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm12.png',
  },
  platehelm13: {
    id:     'platehelm13',
    name:   'Plate Helm XIII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm13.png',
  },

  crown1: {
    id:     'crown1',
    name:   'Crown',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown1.png',
  },
  crown2: {
    id:     'crown2',
    name:   'Crown II',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown2.png',
  },
  crown3: {
    id:     'crown3',
    name:   'Crown III',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown3.png',
  },
  crown4: {
    id:     'crown4',
    name:   'Crown IV',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown4.png',
  },
  crown5: {
    id:     'crown5',
    name:   'Crown V',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown5.png',
  },
  crown6: {
    id:     'crown6',
    name:   'Crown VI',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown6.png',
  },
  crown7: {
    id:     'crown7',
    name:   'Crown VII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown7.png',
  },
  crown8: {
    id:     'crown8',
    name:   'Crown VIII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown8.png',
  },
  crown9: {
    id:     'crown9',
    name:   'Crown IX',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown9.png',
  },
  crown10: {
    id:     'crown10',
    name:   'Crown X',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown10.png',
  },
  crown11: {
    id:     'crown11',
    name:   'Crown XI',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown11.png',
  },
  crown12: {
    id:     'crown12',
    name:   'Crown XII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown12.png',
  },
  crown13: {
    id:     'crown13',
    name:   'Crown XIII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown13.png',
  },
  crown14: {
    id:     'crown14',
    name:   'Crown XIV',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown14.png',
  },
  crown15: {
    id:     'crown15',
    name:   'Crown XV',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown15.png',
  },

  belt1: {
    id:     'belt1',
    name:   'Belt',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt1.png',
  },
  belt2: {
    id:     'belt2',
    name:   'Belt II',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt2.png',
  },
  belt3: {
    id:     'belt3',
    name:   'Belt III',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt3.png',
  },
  belt4: {
    id:     'belt4',
    name:   'Belt IV',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt4.png',
  },
  belt5: {
    id:     'belt5',
    name:   'Belt V',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt5.png',
  },
  belt6: {
    id:     'belt6',
    name:   'Belt VI',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt6.png',
  },
  belt7: {
    id:     'belt7',
    name:   'Belt VII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt7.png',
  },
  belt8: {
    id:     'belt8',
    name:   'Belt VIII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt8.png',
  },
  belt9: {
    id:     'belt9',
    name:   'Belt IX',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt9.png',
  },
  belt10: {
    id:     'belt10',
    name:   'Belt X',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt10.png',
  },
  belt11: {
    id:     'belt11',
    name:   'Belt XI',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt11.png',
  },
  belt12: {
    id:     'belt12',
    name:   'Belt XII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt12.png',
  },
  belt13: {
    id:     'belt13',
    name:   'Belt XIII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt13.png',
  },
  belt14: {
    id:     'belt14',
    name:   'Belt XIV',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt14.png',
  },
  belt15: {
    id:     'belt15',
    name:   'Belt XV',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt15.png',
  },
  belt16: {
    id:     'belt16',
    name:   'Belt XVI',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt16.png',
  },
  belt17: {
    id:     'belt17',
    name:   'Belt XVII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt17.png',
  },
  belt18: {
    id:     'belt18',
    name:   'Belt XVIII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt18.png',
  },
  belt19: {
    id:     'belt19',
    name:   'Belt XIX',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt19.png',
  },

  necklace1: {
    id:     'necklace1',
    name:   'Necklace',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace1.png',
  },
  necklace2: {
    id:     'necklace2',
    name:   'Necklace II',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace2.png',
  },
  necklace3: {
    id:     'necklace3',
    name:   'Necklace III',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace3.png',
  },
  necklace4: {
    id:     'necklace4',
    name:   'Necklace IV',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace4.png',
  },
  necklace5: {
    id:     'necklace5',
    name:   'Necklace V',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace5.png',
  },
  necklace6: {
    id:     'necklace6',
    name:   'Necklace VI',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace6.png',
  },
  necklace7: {
    id:     'necklace7',
    name:   'Necklace VII',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace7.png',
  },
  necklace8: {
    id:     'necklace8',
    name:   'Necklace VIII',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace8.png',
  },
  necklace9: {
    id:     'necklace9',
    name:   'Necklace IX',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace9.png',
  },
  necklace10: {
    id:     'necklace10',
    name:   'Necklace X',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace10.png',
  },
  necklace11: {
    id:     'necklace11',
    name:   'Necklace XI',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace11.png',
  },

  clothshirt1: {
    id:     'clothshirt1',
    name:   'Cloth Shirt',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt1.png',
    ac:     0,
  },
  clothshirt2: {
    id:     'clothshirt2',
    name:   'Cloth Shirt II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt2.png',
    ac:     0,
  },
  clothshirt3: {
    id:     'clothshirt3',
    name:   'Cloth Shirt III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt3.png',
    ac:     0,
  },
  clothshirt4: {
    id:     'clothshirt4',
    name:   'Cloth Shirt IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt4.png',
    ac:     0,
  },
  clothshirt5: {
    id:     'clothshirt5',
    name:   'Cloth Shirt V',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt5.png',
    ac:     0,
  },
  clothshirt6: {
    id:     'clothshirt6',
    name:   'Cloth Shirt VI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt6.png',
    ac:     0,
  },
  clothshirt7: {
    id:     'clothshirt7',
    name:   'Cloth Shirt VII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt7.png',
    ac:     0,
  },
  clothshirt8: {
    id:     'clothshirt8',
    name:   'Cloth Shirt VIII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt8.png',
    ac:     0,
  },

  robe1: {
    id:     'robe1',
    name:   'Robe',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe1.png',
  },
  robe2: {
    id:     'robe2',
    name:   'Robe II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe2.png',
  },
  robe3: {
    id:     'robe3',
    name:   'Robe III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe3.png',
  },
  robe4: {
    id:     'robe4',
    name:   'Robe IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe4.png',
  },
  robe5: {
    id:     'robe5',
    name:   'Robe V',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe5.png',
  },
  robe6: {
    id:     'robe6',
    name:   'Robe VI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe6.png',
  },
  robe7: {
    id:     'robe7',
    name:   'Robe VII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe7.png',
  },
  robe8: {
    id:     'robe8',
    name:   'Robe VIII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe8.png',
  },
  robe9: {
    id:     'robe9',
    name:   'Robe IX',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe9.png',
  },
  robe10: {
    id:     'robe10',
    name:   'Robe X',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe10.png',
  },
  robe11: {
    id:     'robe11',
    name:   'Robe XI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe11.png',
  },

  glvoes1: {
    id:     'glvoes1',
    name:   'Gloves',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/glvoes1.png',
  },
  clothgloves1: {
    id:     'clothgloves1',
    name:   'Cloth Gloves',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves1.png',
  },
  clothgloves2: {
    id:     'clothgloves2',
    name:   'Cloth Gloves II',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves2.png',
  },
  clothgloves3: {
    id:     'clothgloves3',
    name:   'Cloth Gloves III',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves3.png',
  },
  clothgloves4: {
    id:     'clothgloves4',
    name:   'Cloth Gloves IV',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves4.png',
  },
  clothgloves5: {
    id:     'clothgloves5',
    name:   'Cloth Gloves V',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves5.png',
  },
  clothgloves6: {
    id:     'clothgloves6',
    name:   'Cloth Gloves VI',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves6.png',
  },
  clothgloves7: {
    id:     'clothgloves7',
    name:   'Cloth Gloves VII',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves7.png',
  },
  clothgloves8: {
    id:     'clothgloves8',
    name:   'Cloth Gloves VIII',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves8.png',
  },
  clothgloves9: {
    id:     'clothgloves9',
    name:   'Cloth Gloves IX',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves9.png',
  },

  wrist1: {
    id:     'wrist1',
    name:   'Bracer',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist1.png',
  },
  wrist2: {
    id:     'wrist2',
    name:   'Bracer II',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist2.png',
  },
  wrist3: {
    id:     'wrist3',
    name:   'Bracer III',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist3.png',
  },
  wrist4: {
    id:     'wrist4',
    name:   'Bracer IV',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist4.png',
  },
  wrist5: {
    id:     'wrist5',
    name:   'Bracer V',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist5.png',
  },
  wrist6: {
    id:     'wrist6',
    name:   'Bracer VI',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist6.png',
  },
  wrist7: {
    id:     'wrist7',
    name:   'Bracer VII',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist7.png',
  },
  wrist8: {
    id:     'wrist8',
    name:   'Bracer VIII',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist8.png',
  },
  wrist9: {
    id:     'wrist9',
    name:   'Bracer IX',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist9.png',
  },
  wrist10: {
    id:     'wrist10',
    name:   'Bracer X',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist10.png',
  },
  wrist11: {
    id:     'wrist11',
    name:   'Bracer XI',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist11.png',
  },
  wrist12: {
    id:     'wrist12',
    name:   'Bracer XII',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist12.png',
  },

  ring1: {
    id:     'ring1',
    name:   'Ring',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring1.png',
  },
  ring2: {
    id:     'ring2',
    name:   'Ring II',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring2.png',
  },
  ring3: {
    id:     'ring3',
    name:   'Ring III',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring3.png',
  },
  ring4: {
    id:     'ring4',
    name:   'Ring IV',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring4.png',
  },
  ring5: {
    id:     'ring5',
    name:   'Ring V',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring5.png',
  },
  ring6: {
    id:     'ring6',
    name:   'Ring VI',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring6.png',
  },
  ring7: {
    id:     'ring7',
    name:   'Ring VII',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring7.png',
  },
  ring8: {
    id:     'ring8',
    name:   'Ring VIII',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring8.png',
  },
  ring9: {
    id:     'ring9',
    name:   'Ring IX',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring9.png',
  },
  ring10: {
    id:     'ring10',
    name:   'Ring X',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring10.png',
  },
  ring11: {
    id:     'ring11',
    name:   'Ring XI',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring11.png',
  },
  ring12: {
    id:     'ring12',
    name:   'Ring XII',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring12.png',
  },
  ring13: {
    id:     'ring13',
    name:   'Ring XIII',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring13.png',
  },
  ring14: {
    id:     'ring14',
    name:   'Ring XIV',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring14.png',
  },
  ring15: {
    id:     'ring15',
    name:   'Ring XV',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring15.png',
  },

  leatherboots1: {
    id:     'leatherboots1',
    name:   'Leather Boots',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots1.png',
    ac:     1,
  },
  leatherboots2: {
    id:     'leatherboots2',
    name:   'Leather Boots II',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots2.png',
    ac:     1,
  },
  leatherboots3: {
    id:     'leatherboots3',
    name:   'Leather Boots III',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots3.png',
    ac:     1,
  },
  leatherboots4: {
    id:     'leatherboots4',
    name:   'Leather Boots IV',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots4.png',
    ac:     1,
  },
  leatherboots5: {
    id:     'leatherboots5',
    name:   'Leather Boots V',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots5.png',
    ac:     1,
  },
  leatherboots6: {
    id:     'leatherboots6',
    name:   'Leather Boots VI',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots6.png',
    ac:     1,
  },
  leatherboots7: {
    id:     'leatherboots7',
    name:   'Leather Boots VII',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots7.png',
    ac:     1,
  },
  sandals1: {
    id:     'sandals1',
    name:   'Sandals',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals1.png',
  },
  sandals2: {
    id:     'sandals2',
    name:   'Sandals II',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals2.png',
  },
  sandals3: {
    id:     'sandals3',
    name:   'Sandals III',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals3.png',
  },
  sandals4: {
    id:     'sandals4',
    name:   'Sandals IV',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals4.png',
  },
  sandals5: {
    id:     'sandals5',
    name:   'Sandals V',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals5.png',
  },
  sandals6: {
    id:     'sandals6',
    name:   'Sandals VI',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals6.png',
  },
  sandals7: {
    id:     'sandals7',
    name:   'Sandals VII',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals7.png',
  },
  sandals8: {
    id:     'sandals8',
    name:   'Sandals VIII',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals8.png',
  },
  sandals9: {
    id:     'sandals9',
    name:   'Sandals IX',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals9.png',
  },
  mixedboots1: {
    id:     'mixedboots1',
    name:   'Mixed Boots',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedboots1.png',
    ac:     2,
  },
  mixedboots2: {
    id:     'mixedboots2',
    name:   'Mixed Boots II',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedboots2.png',
    ac:     2,
  },
  mixedboots3: {
    id:     'mixedboots3',
    name:   'Mixed Boots III',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedboots3.png',
    ac:     2,
  },
  plateboots1: {
    id:     'plateboots1',
    name:   'Plate Boots',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots1.png',
    ac:     3,
  },
  plateboots2: {
    id:     'plateboots2',
    name:   'Plate Boots II',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots2.png',
    ac:     3,
  },
  plateboots3: {
    id:     'plateboots3',
    name:   'Plate Boots III',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots3.png',
    ac:     3,
  },
  plateboots4: {
    id:     'plateboots4',
    name:   'Plate Boots IV',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots4.png',
    ac:     3,
  },
  plateboots5: {
    id:     'plateboots5',
    name:   'Plate Boots V',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots5.png',
    ac:     3,
  },
  plateboots6: {
    id:     'plateboots6',
    name:   'Plate Boots VI',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots6.png',
    ac:     3,
  },
  plateboots7: {
    id:     'plateboots7',
    name:   'Plate Boots VII',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots7.png',
    ac:     3,
  },
  plateboots8: {
    id:     'plateboots8',
    name:   'Plate Boots VIII',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots8.png',
    ac:     3,
  },
  plateboots9: {
    id:     'plateboots9',
    name:   'Plate Boots IX',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots9.png',
    ac:     3,
  },

  mixedgloves1: {
    id:     'mixedgloves1',
    name:   'Mixed Gloves',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedgloves1.png',
  },
  mixedgloves2: {
    id:     'mixedgloves2',
    name:   'Mixed Gloves II',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedgloves2.png',
  },
  mixedgloves3: {
    id:     'mixedgloves3',
    name:   'Mixed Gloves III',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedgloves3.png',
  },
  mixedgloves4: {
    id:     'mixedgloves4',
    name:   'Mixed Gloves IV',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedgloves4.png',
  },
  plategloves1: {
    id:     'plategloves1',
    name:   'Plate Gauntlets',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/plategloves1.png',
  },
  plategloves2: {
    id:     'plategloves2',
    name:   'Plate Gauntlets II',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/plategloves2.png',
  },
  plategloves3: {
    id:     'plategloves3',
    name:   'Plate Gauntlets III',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/plategloves3.png',
  },
  plategloves4: {
    id:     'plategloves4',
    name:   'Plate Gauntlets IV',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/plategloves4.png',
  },
  plategloves5: {
    id:     'plategloves5',
    name:   'Plate Gauntlets V',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/plategloves5.png',
  },

  leatherwrist1: {
    id:     'leatherwrist1',
    name:   'Leather Bracer',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherwrist1.png',
  },
  leatherwrist2: {
    id:     'leatherwrist2',
    name:   'Leather Bracer II',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherwrist2.png',
  },
  mixedwrist1: {
    id:     'mixedwrist1',
    name:   'Mixed Bracer',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedwrist1.png',
  },
  mixedwrist2: {
    id:     'mixedwrist2',
    name:   'Mixed Bracer II',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedwrist2.png',
  },
  mixedwrist3: {
    id:     'mixedwrist3',
    name:   'Mixed Bracer III',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedwrist3.png',
  },
  mixedwrist4: {
    id:     'mixedwrist4',
    name:   'Mixed Bracer IV',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedwrist4.png',
  },
  platewrist1: {
    id:     'platewrist1',
    name:   'Plate Bracer',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist1.png',
  },
  platewrist2: {
    id:     'platewrist2',
    name:   'Plate Bracer II',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist2.png',
  },
  platewrist3: {
    id:     'platewrist3',
    name:   'Plate Bracer III',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist3.png',
  },
  platewrist4: {
    id:     'platewrist4',
    name:   'Plate Bracer IV',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist4.png',
  },
  platewrist5: {
    id:     'platewrist5',
    name:   'Plate Bracer V',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist5.png',
  },
  platewrist6: {
    id:     'platewrist6',
    name:   'Plate Bracer VI',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist6.png',
  },

  cloak1: {
    id:     'cloak1',
    name:   'Cloak',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak1.png',
  },
  cloak2: {
    id:     'cloak2',
    name:   'Cloak II',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak2.png',
  },
  cloak3: {
    id:     'cloak3',
    name:   'Cloak III',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak3.png',
  },
  cloak4: {
    id:     'cloak4',
    name:   'Cloak IV',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak4.png',
  },
  cloak5: {
    id:     'cloak5',
    name:   'Cloak V',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak5.png',
  },
  cloak6: {
    id:     'cloak6',
    name:   'Cloak VI',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak6.png',
  },
  cloak7: {
    id:     'cloak7',
    name:   'Cloak VII',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak7.png',
  },
  cloak8: {
    id:     'cloak8',
    name:   'Cloak VIII',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak8.png',
  },
  cloak9: {
    id:     'cloak9',
    name:   'Cloak IX',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak9.png',
  },
  cloak10: {
    id:     'cloak10',
    name:   'Cloak X',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak10.png',
  },
  cloak11: {
    id:     'cloak11',
    name:   'Cloak XI',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak11.png',
  },
  cloak12: {
    id:     'cloak12',
    name:   'Cloak XII',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak12.png',
  },
  cloak13: {
    id:     'cloak13',
    name:   'Cloak XIII',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak13.png',
  },

  leathergloves1: {
    id:     'leathergloves1',
    name:   'Leather Gloves',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves1.png',
  },
  leathergloves2: {
    id:     'leathergloves2',
    name:   'Leather Gloves II',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves2.png',
  },
  leathergloves3: {
    id:     'leathergloves3',
    name:   'Leather Gloves III',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves3.png',
  },
  leathergloves4: {
    id:     'leathergloves4',
    name:   'Leather Gloves IV',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves4.png',
  },
  leathergloves5: {
    id:     'leathergloves5',
    name:   'Leather Gloves V',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves5.png',
  },
  leathergloves6: {
    id:     'leathergloves6',
    name:   'Leather Gloves VI',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves6.png',
  },
  leathergloves7: {
    id:     'leathergloves7',
    name:   'Leather Gloves VII',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves7.png',
  },
  leathergloves8: {
    id:     'leathergloves8',
    name:   'Leather Gloves VIII',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves8.png',
  },
};

export function getItem(id) {
  const def = ITEMS[id];
  return def ? { ...def } : null;
}
