// js/items.js — equippable item catalog (see js/equipment.js for the item schema)

export const ITEMS = {
  // ⚠ `slots` is what MAKES a bag a container — it is not optional decoration. The equipment
  // panel gates the contents view on `item?.slots` (ui.js), and placeInFirstEmptyBagSlot skips
  // any bag without it, so a bag missing this field equips, draws its icon, and is then inert:
  // it opens nothing and carries nothing. bag2–bag11 shipped without it and every DROPPED bag
  // was dead weight; only bag1 worked, because it's the hand-assigned startingEquipment bag.
  // Every bag carries 10 — these are art variants, and per the convention above a variant
  // changes WHICH one you get, never how much it holds. Any new bag needs this line too.
  bag1: {
    id:     'bag1',
    name:   'Bag',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag1.png',
    slots:  10,
  },
  bag2: {
    id:     'bag2',
    name:   'Bag II',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag2.png',
    slots:  10,
  },
  bag3: {
    id:     'bag3',
    name:   'Bag III',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag3.png',
    slots:  10,
  },
  bag4: {
    id:     'bag4',
    name:   'Bag IV',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag4.png',
    slots:  10,
  },
  bag5: {
    id:     'bag5',
    name:   'Bag V',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag5.png',
    slots:  10,
  },
  bag6: {
    id:     'bag6',
    name:   'Bag VI',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag6.png',
    slots:  10,
  },
  bag7: {
    id:     'bag7',
    name:   'Bag VII',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag7.png',
    slots:  10,
  },
  bag8: {
    id:     'bag8',
    name:   'Bag VIII',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag8.png',
    slots:  10,
  },
  bag9: {
    id:     'bag9',
    name:   'Bag IX',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag9.png',
    slots:  10,
  },
  bag10: {
    id:     'bag10',
    name:   'Bag X',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag10.png',
    slots:  10,
  },
  bag11: {
    id:     'bag11',
    name:   'Bag XI',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag11.png',
    slots:  10,
  },

  handaxe: {
    id:     'handaxe',
    name:   'Handaxe',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/handaxe.png',
    dmg:    '1d6',
    dmgType: 'slashing',
    light: true,
    thrown: true,
    weaponType: 'Handaxe',
    category: 'simple',
  },
  battleaxe: {
    id:     'battleaxe',
    name:   'Battleaxe',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/battleaxe.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
    weaponType: 'Battleaxe',
    category: 'martial',
  },
  greataxe: {
    id:     'greataxe',
    name:   'Greataxe',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/greataxe.png',
    dmg:    '1d12',
    dmgType: 'slashing',
    heavy: true,
    twoHanded: true,
    weaponType: 'Greataxe',
    category: 'martial',
  },

  // ── Axe variants ────────────────────────────────────────────────────────────
  // The axe1..axe9 art was the only unused asset set on disk (7 files; axe3/axe8 don't
  // exist, hence the gaps). Each reuses one of the three axe archetypes above rather than
  // inventing new stat shapes — a drop's power comes from its rolled rarity/affixes, not
  // from the base, so more bases means more VARIETY, not more numbers to balance.
  greataxe2: {
    id:     'greataxe2',
    name:   'Greataxe II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/greataxe2.png',
    dmg:    '1d12',
    dmgType: 'slashing',
    heavy: true,
    twoHanded: true,
    weaponType: 'Greataxe',
    category: 'martial',
  },
  handaxe1: {
    id:     'handaxe1',
    name:   'Handaxe II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/handaxe1.png',
    dmg:    '1d6',
    dmgType: 'slashing',
    light: true,
    thrown: true,
    weaponType: 'Handaxe',
    category: 'simple',
  },
  greataxe3: {
    id:     'greataxe3',
    name:   'Greataxe III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/greataxe3.png',
    dmg:    '1d12',
    dmgType: 'slashing',
    heavy: true,
    twoHanded: true,
    weaponType: 'Greataxe',
    category: 'martial',
  },
  battleaxe3: {
    id:     'battleaxe3',
    name:   'Battleaxe III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/battleaxe3.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
    weaponType: 'Battleaxe',
    category: 'martial',
  },
  battleaxe4: {
    id:     'battleaxe4',
    name:   'Battleaxe IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/battleaxe4.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
    weaponType: 'Battleaxe',
    category: 'martial',
  },
  handaxe2: {
    id:     'handaxe2',
    name:   'Handaxe III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/handaxe2.png',
    dmg:    '1d6',
    dmgType: 'slashing',
    light: true,
    thrown: true,
    weaponType: 'Handaxe',
    category: 'simple',
  },
  battleaxe2: {
    id:     'battleaxe2',
    name:   'Battleaxe II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/battleaxe2.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
    weaponType: 'Battleaxe',
    category: 'martial',
  },

  warhammer1: {
    id:     'warhammer1',
    name:   'Warhammer',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer1.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
    weaponType: 'Warhammer',
    category: 'martial',
  },
  warhammer2: {
    id:     'warhammer2',
    name:   'Warhammer II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer2.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
    weaponType: 'Warhammer',
    category: 'martial',
  },
  warhammer3: {
    id:     'warhammer3',
    name:   'Warhammer III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer3.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
    weaponType: 'Warhammer',
    category: 'martial',
  },
  lighthammer4: {
    id:     'lighthammer4',
    name:   'Light Hammer IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/lighthammer4.png',
    dmg:    '1d4',
    dmgType: 'bludgeoning',
    light: true,
    thrown: true,
    weaponType: 'Light Hammer',
    category: 'simple',
  },
  warhammer5: {
    id:     'warhammer5',
    name:   'Warhammer IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer5.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
    weaponType: 'Warhammer',
    category: 'martial',
  },
  lighthammer3: {
    id:     'lighthammer3',
    name:   'Light Hammer III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/lighthammer3.png',
    dmg:    '1d4',
    dmgType: 'bludgeoning',
    light: true,
    thrown: true,
    weaponType: 'Light Hammer',
    category: 'simple',
  },
  warhammer7: {
    id:     'warhammer7',
    name:   'Warhammer V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer7.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
    weaponType: 'Warhammer',
    category: 'martial',
  },
  warhammer8: {
    id:     'warhammer8',
    name:   'Warhammer VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer8.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
    versatile: '1d10',
    weaponType: 'Warhammer',
    category: 'martial',
  },
  lighthammer2: {
    id:     'lighthammer2',
    name:   'Light Hammer II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/lighthammer2.png',
    dmg:    '1d4',
    dmgType: 'bludgeoning',
    light: true,
    thrown: true,
    weaponType: 'Light Hammer',
    category: 'simple',
  },
  lighthammer1: {
    id:     'lighthammer1',
    name:   'Light Hammer',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/lighthammer1.png',
    dmg:    '1d4',
    dmgType: 'bludgeoning',
    light: true,
    thrown: true,
    weaponType: 'Light Hammer',
    category: 'simple',
  },

  greatsword1: {
    id:     'greatsword1',
    name:   'Greatsword',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/greatsword1.png',
    dmg:    '2d6',
    dmgType: 'slashing',
    heavy: true,
    twoHanded: true,
    weaponType: 'Greatsword',
    category: 'martial',
  },
  shortsword2: {
    id:     'shortsword2',
    name:   'Shortsword II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shortsword2.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    light: true,
    finesse: true,
    weaponType: 'Shortsword',
    category: 'martial',
  },
  greatsword2: {
    id:     'greatsword2',
    name:   'Greatsword II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/greatsword2.png',
    dmg:    '2d6',
    dmgType: 'slashing',
    heavy: true,
    twoHanded: true,
    weaponType: 'Greatsword',
    category: 'martial',
  },
  longsword1: {
    id:     'longsword1',
    name:   'Longsword',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/longsword1.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
    weaponType: 'Longsword',
    category: 'martial',
  },
  shortsword3: {
    id:     'shortsword3',
    name:   'Shortsword III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shortsword3.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    light: true,
    finesse: true,
    weaponType: 'Shortsword',
    category: 'martial',
  },
  shortsword1: {
    id:     'shortsword1',
    name:   'Shortsword',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shortsword1.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    light: true,
    finesse: true,
    weaponType: 'Shortsword',
    category: 'martial',
  },
  longsword2: {
    id:     'longsword2',
    name:   'Longsword II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/longsword2.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
    weaponType: 'Longsword',
    category: 'martial',
  },
  longsword3: {
    id:     'longsword3',
    name:   'Longsword III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/longsword3.png',
    dmg:    '1d8',
    dmgType: 'slashing',
    versatile: '1d10',
    weaponType: 'Longsword',
    category: 'martial',
  },

  stave1: {
    id:     'stave1',
    name:   'Quarterstaff',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave1.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
    weaponType: 'Quarterstaff',
    category: 'simple',
  },
  stave2: {
    id:     'stave2',
    name:   'Quarterstaff II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave2.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
    weaponType: 'Quarterstaff',
    category: 'simple',
  },
  stave3: {
    id:     'stave3',
    name:   'Quarterstaff III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave3.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
    weaponType: 'Quarterstaff',
    category: 'simple',
  },
  stave4: {
    id:     'stave4',
    name:   'Quarterstaff IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave4.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
    weaponType: 'Quarterstaff',
    category: 'simple',
  },
  stave5: {
    id:     'stave5',
    name:   'Quarterstaff V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave5.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
    weaponType: 'Quarterstaff',
    category: 'simple',
  },
  stave6: {
    id:     'stave6',
    name:   'Quarterstaff VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave6.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
    weaponType: 'Quarterstaff',
    category: 'simple',
  },
  stave7: {
    id:     'stave7',
    name:   'Quarterstaff VII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave7.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
    weaponType: 'Quarterstaff',
    category: 'simple',
  },
  stave8: {
    id:     'stave8',
    name:   'Quarterstaff VIII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave8.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
    versatile: '1d8',
    weaponType: 'Quarterstaff',
    category: 'simple',
  },

  wand1: {
    id:     'wand1',
    name:   'Wand',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand1.png',
    focus: true,
  },
  wand2: {
    id:     'wand2',
    name:   'Wand II',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand2.png',
    focus: true,
  },
  wand3: {
    id:     'wand3',
    name:   'Wand III',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand3.png',
    focus: true,
  },
  wand4: {
    id:     'wand4',
    name:   'Wand IV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand4.png',
    focus: true,
  },
  wand5: {
    id:     'wand5',
    name:   'Wand V',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand5.png',
    focus: true,
  },
  wand6: {
    id:     'wand6',
    name:   'Wand VI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand6.png',
    focus: true,
  },
  wand7: {
    id:     'wand7',
    name:   'Wand VII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand7.png',
    focus: true,
  },
  wand8: {
    id:     'wand8',
    name:   'Wand VIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand8.png',
    focus: true,
  },
  wand9: {
    id:     'wand9',
    name:   'Wand IX',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand9.png',
    focus: true,
  },
  wand10: {
    id:     'wand10',
    name:   'Wand X',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand10.png',
    focus: true,
  },
  wand11: {
    id:     'wand11',
    name:   'Wand XI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand11.png',
    focus: true,
  },
  wand12: {
    id:     'wand12',
    name:   'Wand XII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand12.png',
    focus: true,
  },

  orb1: {
    id:     'orb1',
    name:   'Orb',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb1.png',
    focus: true,
  },
  orb2: {
    id:     'orb2',
    name:   'Orb II',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb2.png',
    focus: true,
  },
  orb3: {
    id:     'orb3',
    name:   'Orb III',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb3.png',
    focus: true,
  },
  orb4: {
    id:     'orb4',
    name:   'Orb IV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb4.png',
    focus: true,
  },
  orb5: {
    id:     'orb5',
    name:   'Orb V',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb5.png',
    focus: true,
  },
  orb6: {
    id:     'orb6',
    name:   'Orb VI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb6.png',
    focus: true,
  },
  orb7: {
    id:     'orb7',
    name:   'Orb VII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb7.png',
    focus: true,
  },
  orb8: {
    id:     'orb8',
    name:   'Orb VIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb8.png',
    focus: true,
  },
  orb9: {
    id:     'orb9',
    name:   'Orb IX',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb9.png',
    focus: true,
  },
  orb10: {
    id:     'orb10',
    name:   'Orb X',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb10.png',
    focus: true,
  },
  orb11: {
    id:     'orb11',
    name:   'Orb XI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb11.png',
    focus: true,
  },
  orb12: {
    id:     'orb12',
    name:   'Orb XII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb12.png',
    focus: true,
  },
  orb13: {
    id:     'orb13',
    name:   'Orb XIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb13.png',
    focus: true,
  },
  orb14: {
    id:     'orb14',
    name:   'Orb XIV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb14.png',
    focus: true,
  },
  orb15: {
    id:     'orb15',
    name:   'Orb XV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb15.png',
    focus: true,
  },

  shield1: {
    id:     'shield1',
    name:   'Shield',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield1.png',
    ac:     2,
  },
  shield2: {
    id:     'shield2',
    name:   'Shield II',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield2.png',
    ac:     2,
  },
  shield3: {
    id:     'shield3',
    name:   'Shield III',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield3.png',
    ac:     2,
  },
  shield4: {
    id:     'shield4',
    name:   'Shield IV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield4.png',
    ac:     2,
  },
  shield5: {
    id:     'shield5',
    name:   'Shield V',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield5.png',
    ac:     2,
  },
  shield6: {
    id:     'shield6',
    name:   'Shield VI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield6.png',
    ac:     2,
  },
  shield7: {
    id:     'shield7',
    name:   'Shield VII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield7.png',
    ac:     2,
  },
  shield8: {
    id:     'shield8',
    name:   'Shield VIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield8.png',
    ac:     2,
  },
  shield9: {
    id:     'shield9',
    name:   'Shield IX',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield9.png',
    ac:     2,
  },
  shield10: {
    id:     'shield10',
    name:   'Shield X',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield10.png',
    ac:     2,
  },
  shield11: {
    id:     'shield11',
    name:   'Shield XI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield11.png',
    ac:     2,
  },
  shield12: {
    id:     'shield12',
    name:   'Shield XII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield12.png',
    ac:     2,
  },
  shield13: {
    id:     'shield13',
    name:   'Shield XIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield13.png',
    ac:     2,
  },
  shield14: {
    id:     'shield14',
    name:   'Shield XIV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield14.png',
    ac:     2,
  },
  shield15: {
    id:     'shield15',
    name:   'Shield XV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shield15.png',
    ac:     2,
  },

  dagger1: {
    id:     'dagger1',
    name:   'Dagger',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger1.png',
    dmg:    '1d4',
    dmgType: 'piercing',
    light: true,
    thrown: true,
    finesse: true,
    weaponType: 'Dagger',
    category: 'simple',
  },
  dagger2: {
    id:     'dagger2',
    name:   'Dagger II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger2.png',
    dmg:    '1d4',
    dmgType: 'piercing',
    light: true,
    thrown: true,
    finesse: true,
    weaponType: 'Dagger',
    category: 'simple',
  },
  dagger3: {
    id:     'dagger3',
    name:   'Dagger III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger3.png',
    dmg:    '1d4',
    dmgType: 'piercing',
    light: true,
    thrown: true,
    finesse: true,
    weaponType: 'Dagger',
    category: 'simple',
  },
  dagger4: {
    id:     'dagger4',
    name:   'Dagger IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger4.png',
    dmg:    '1d4',
    dmgType: 'piercing',
    light: true,
    thrown: true,
    finesse: true,
    weaponType: 'Dagger',
    category: 'simple',
  },
  dagger5: {
    id:     'dagger5',
    name:   'Dagger V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger5.png',
    dmg:    '1d4',
    dmgType: 'piercing',
    light: true,
    thrown: true,
    finesse: true,
    weaponType: 'Dagger',
    category: 'simple',
  },
  dagger6: {
    id:     'dagger6',
    name:   'Dagger VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger6.png',
    dmg:    '1d4',
    dmgType: 'piercing',
    light: true,
    thrown: true,
    finesse: true,
    weaponType: 'Dagger',
    category: 'simple',
  },

  longbow1: {
    id:     'longbow1',
    name:   'Longbow',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/longbow1.png',
    dmg:    '1d8',
    dmgType: 'piercing',
    heavy: true,
    twoHanded: true,
    ammunition: true,
    weaponType: 'Longbow',
    category: 'martial',
  },
  longbow2: {
    id:     'longbow2',
    name:   'Longbow II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/longbow2.png',
    dmg:    '1d8',
    dmgType: 'piercing',
    heavy: true,
    twoHanded: true,
    ammunition: true,
    weaponType: 'Longbow',
    category: 'martial',
  },
  shortbow3: {
    id:     'shortbow3',
    name:   'Shortbow III',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shortbow3.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    twoHanded: true,
    ammunition: true,
    weaponType: 'Shortbow',
    category: 'simple',
  },
  shortbow: {
    id:     'shortbow',
    name:   'Shortbow',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shortbow.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    twoHanded: true,
    ammunition: true,
    weaponType: 'Shortbow',
    category: 'simple',
  },
  longbow5: {
    id:     'longbow5',
    name:   'Longbow III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/longbow5.png',
    dmg:    '1d8',
    dmgType: 'piercing',
    heavy: true,
    twoHanded: true,
    ammunition: true,
    weaponType: 'Longbow',
    category: 'martial',
  },
  shortbow2: {
    id:     'shortbow2',
    name:   'Shortbow II',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/shortbow2.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    twoHanded: true,
    ammunition: true,
    weaponType: 'Shortbow',
    category: 'simple',
  },

  heavycrossbow1: {
    id:     'heavycrossbow1',
    name:   'Heavy Crossbow',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/heavycrossbow1.png',
    dmg:    '1d10',
    dmgType: 'piercing',
    heavy: true,
    twoHanded: true,
    ammunition: true,
    loading: true,
    weaponType: 'Heavy Crossbow',
    category: 'martial',
  },
  heavycrossbow2: {
    id:     'heavycrossbow2',
    name:   'Heavy Crossbow II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/heavycrossbow2.png',
    dmg:    '1d10',
    dmgType: 'piercing',
    heavy: true,
    twoHanded: true,
    ammunition: true,
    loading: true,
    weaponType: 'Heavy Crossbow',
    category: 'martial',
  },
  lightcrossbow: {
    id:     'lightcrossbow',
    name:   'Light Crossbow',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/lightcrossbow.png',
    dmg:    '1d8',
    dmgType: 'piercing',
    twoHanded: true,
    ammunition: true,
    loading: true,
    weaponType: 'Light Crossbow',
    category: 'simple',
  },
  lightcrossbow2: {
    id:     'lightcrossbow2',
    name:   'Light Crossbow II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/lightcrossbow2.png',
    dmg:    '1d8',
    dmgType: 'piercing',
    twoHanded: true,
    ammunition: true,
    loading: true,
    weaponType: 'Light Crossbow',
    category: 'simple',
  },
  heavycrossbow3: {
    id:     'heavycrossbow3',
    name:   'Heavy Crossbow III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/heavycrossbow3.png',
    dmg:    '1d10',
    dmgType: 'piercing',
    heavy: true,
    twoHanded: true,
    ammunition: true,
    loading: true,
    weaponType: 'Heavy Crossbow',
    category: 'martial',
  },
  crossbow6: {
    id:     'crossbow6',
    name:   'Heavy Crossbow IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/crossbow6.png',
    dmg:    '1d10',
    dmgType: 'piercing',
    heavy: true,
    twoHanded: true,
    ammunition: true,
    loading: true,
    weaponType: 'Heavy Crossbow',
    category: 'martial',
  },

  javelin1: {
    id:     'javelin1',
    name:   'Javelin',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/javelin1.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    thrown: true,
    weaponType: 'Javelin',
    category: 'simple',
  },
  javelin2: {
    id:     'javelin2',
    name:   'Javelin II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/javelin2.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    thrown: true,
    weaponType: 'Javelin',
    category: 'simple',
  },
  javelin3: {
    id:     'javelin3',
    name:   'Javelin III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/javelin3.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    thrown: true,
    weaponType: 'Javelin',
    category: 'simple',
  },
  javelin4: {
    id:     'javelin4',
    name:   'Javelin IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/javelin4.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    thrown: true,
    weaponType: 'Javelin',
    category: 'simple',
  },
  javelin5: {
    id:     'javelin5',
    name:   'Javelin V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/javelin5.png',
    dmg:    '1d6',
    dmgType: 'piercing',
    thrown: true,
    weaponType: 'Javelin',
    category: 'simple',
  },

  // ── Chest armor ────────────────────────────────────────────────────────────
  // AC and category come from the D&D armor table. `armorType` is the load-bearing field:
  // computeAC reads it to decide how much DEX the armor lets you keep (see ARMOR_DEX_CAP),
  // and the tooltip reads it to print "Medium Armor · AC 14 + Dex modifier (max 2)".
  //
  // Breastplate was dropped — its art was deleted, and the table has no Breastplate row.
  // Light — full DEX modifier
  leatherarmor1: {
    id:     'leatherarmor1',
    name:   'Leather Armor',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor1.png',
    ac:     11,
    material: 'leather',
  },
  leatherarmor4: {
    id:     'leatherarmor4',
    name:   'Leather Armor IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor4.png',
    ac:     11,
    material: 'leather',
  },
  leatherarmor5: {
    id:     'leatherarmor5',
    name:   'Leather Armor V',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor5.png',
    ac:     11,
    material: 'leather',
  },
  leatherarmor6: {
    id:     'leatherarmor6',
    name:   'Leather Armor VI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor6.png',
    ac:     11,
    material: 'leather',
  },
  leatherarmor7: {
    id:     'leatherarmor7',
    name:   'Leather Armor VII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor7.png',
    ac:     11,
    material: 'leather',
  },
  leatherarmor9: {
    id:     'leatherarmor9',
    name:   'Leather Armor IX',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor9.png',
    ac:     11,
    material: 'leather',
  },
  leatherarmor10: {
    id:     'leatherarmor10',
    name:   'Leather Armor X',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor10.png',
    ac:     11,
    material: 'leather',
  },
  leatherarmor11: {
    id:     'leatherarmor11',
    name:   'Leather Armor XI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor11.png',
    ac:     11,
    material: 'leather',
  },
  leatherarmor12: {
    id:     'leatherarmor12',
    name:   'Leather Armor XII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor12.png',
    ac:     11,
    material: 'leather',
  },
  leatherarmor13: {
    id:     'leatherarmor13',
    name:   'Leather Armor XIII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor13.png',
    ac:     11,
    material: 'leather',
  },
  leatherarmor14: {
    id:     'leatherarmor14',
    name:   'Leather Armor XIV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor14.png',
    ac:     11,
    material: 'leather',
  },
  leatherarmor15: {
    id:     'leatherarmor15',
    name:   'Leather Armor XV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor15.png',
    ac:     11,
    material: 'leather',
  },
  leatherarmor16: {
    id:     'leatherarmor16',
    name:   'Leather Armor XVI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor16.png',
    ac:     11,
    material: 'leather',
  },
  paddedarmor: {
    id:     'paddedarmor',
    name:   'Padded Armor',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/paddedarmor.png',
    ac:     11,
    material: 'leather',
  },
  paddedarmor2: {
    id:     'paddedarmor2',
    name:   'Padded Armor II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/paddedarmor2.png',
    ac:     11,
    material: 'leather',
  },
  paddedarmor3: {
    id:     'paddedarmor3',
    name:   'Padded Armor III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/paddedarmor3.png',
    ac:     11,
    material: 'leather',
  },
  paddedarmor4: {
    id:     'paddedarmor4',
    name:   'Padded Armor IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/paddedarmor4.png',
    ac:     11,
    material: 'leather',
  },
  studdedleatherarmor1: {
    id:     'studdedleatherarmor1',
    name:   'Studded Leather',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/studdedleatherarmor1.png',
    ac:     12,
    material: 'leather',
  },
  studdedleatherarmor2: {
    id:     'studdedleatherarmor2',
    name:   'Studded Leather II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/studdedleatherarmor2.png',
    ac:     12,
    material: 'leather',
  },
  studdedleatherarmor3: {
    id:     'studdedleatherarmor3',
    name:   'Studded Leather III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/studdedleatherarmor3.png',
    ac:     12,
    material: 'leather',
  },
  // Medium — DEX modifier capped at +2
  hidearmor1: {
    id:     'hidearmor1',
    name:   'Hide Armor',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/hidearmor1.png',
    ac:     12,
    material: 'hide',
  },
  hidearmor2: {
    id:     'hidearmor2',
    name:   'Hide Armor II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/hidearmor2.png',
    ac:     12,
    material: 'hide',
  },
  hidearmor3: {
    id:     'hidearmor3',
    name:   'Hide Armor III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/hidearmor3.png',
    ac:     12,
    material: 'hide',
  },
  hidearmor4: {
    id:     'hidearmor4',
    name:   'Hide Armor IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/hidearmor4.png',
    ac:     12,
    material: 'hide',
  },
  scalearmor1: {
    id:     'scalearmor1',
    name:   'Scale Mail',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/scalearmor1.png',
    ac:     14,
    material: 'hide',
  },
  scalearmor2: {
    id:     'scalearmor2',
    name:   'Scale Mail II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/scalearmor2.png',
    ac:     14,
    material: 'hide',
  },
  scalearmor3: {
    id:     'scalearmor3',
    name:   'Scale Mail III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/scalearmor3.png',
    ac:     14,
    material: 'hide',
  },
  // Heavy — no DEX modifier at all
  ringmail1: {
    id:     'ringmail1',
    name:   'Ring Mail',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/ringmail1.png',
    ac:     14,
    material: 'plate',
  },
  ringmail2: {
    id:     'ringmail2',
    name:   'Ring Mail II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/ringmail2.png',
    ac:     14,
    material: 'plate',
  },
  ringmail3: {
    id:     'ringmail3',
    name:   'Ring Mail III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/ringmail3.png',
    ac:     14,
    material: 'plate',
  },
  ringmail4: {
    id:     'ringmail4',
    name:   'Ring Mail IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/ringmail4.png',
    ac:     14,
    material: 'plate',
  },
  chainarmor1: {
    id:     'chainarmor1',
    name:   'Chain Mail',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/chainarmor1.png',
    ac:     16,
    material: 'plate',
  },
  chainarmor2: {
    id:     'chainarmor2',
    name:   'Chain Mail II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/chainarmor2.png',
    ac:     16,
    material: 'plate',
  },
  chainarmor3: {
    id:     'chainarmor3',
    name:   'Chain Mail III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/chainarmor3.png',
    ac:     16,
    material: 'plate',
  },
  splintmail1: {
    id:     'splintmail1',
    name:   'Splint Armor',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/splintmail1.png',
    ac:     17,
    material: 'plate',
  },
  splintmail2: {
    id:     'splintmail2',
    name:   'Splint Armor II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/splintmail2.png',
    ac:     17,
    material: 'plate',
  },
  splintmail3: {
    id:     'splintmail3',
    name:   'Splint Armor III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/splintmail3.png',
    ac:     17,
    material: 'plate',
  },
  splintmail4: {
    id:     'splintmail4',
    name:   'Splint Armor IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/splintmail4.png',
    ac:     17,
    material: 'plate',
  },
  splintmail5: {
    id:     'splintmail5',
    name:   'Splint Armor V',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/splintmail5.png',
    ac:     17,
    material: 'plate',
  },
  platearmor1: {
    id:     'platearmor1',
    name:   'Plate Armor',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/platearmor1.png',
    ac:     18,
    material: 'plate',
  },
  platearmor2: {
    id:     'platearmor2',
    name:   'Plate Armor II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/platearmor2.png',
    ac:     18,
    material: 'plate',
  },
  platearmor3: {
    id:     'platearmor3',
    name:   'Plate Armor III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/platearmor3.png',
    ac:     18,
    material: 'plate',
  },
  platearmor4: {
    id:     'platearmor4',
    name:   'Plate Armor IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/platearmor4.png',
    ac:     18,
    material: 'plate',
  },

  chainlegs1: {
    id:     'chainlegs1',
    name:   'Simple Chain Legs',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/chainlegs1.png',
    material: 'plate',
  },
  leatherlegs1: {
    id:     'leatherlegs1',
    name:   'Leather Leggings',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs1.png',
    material: 'leather',
  },
  leatherlegs2: {
    id:     'leatherlegs2',
    name:   'Leather Leggings II',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs2.png',
    material: 'leather',
  },
  leatherlegs3: {
    id:     'leatherlegs3',
    name:   'Leather Leggings III',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs3.png',
    material: 'leather',
  },
  leatherlegs4: {
    id:     'leatherlegs4',
    name:   'Leather Leggings IV',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs4.png',
    material: 'leather',
  },
  leatherlegs5: {
    id:     'leatherlegs5',
    name:   'Leather Leggings V',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs5.png',
    material: 'leather',
  },
  leatherlegs6: {
    id:     'leatherlegs6',
    name:   'Leather Leggings VI',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs6.png',
    material: 'leather',
  },
  mixedlegs1: {
    id:     'mixedlegs1',
    name:   'Mixed Leggings',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedlegs1.png',
    material: 'hide',
  },
  mixedlegs2: {
    id:     'mixedlegs2',
    name:   'Mixed Leggings II',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedlegs2.png',
    material: 'hide',
  },
  mixedlegs3: {
    id:     'mixedlegs3',
    name:   'Mixed Leggings III',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedlegs3.png',
    material: 'hide',
  },
  platelegs1: {
    id:     'platelegs1',
    name:   'Plate Greaves',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/platelegs1.png',
    material: 'plate',
  },
  platelegs2: {
    id:     'platelegs2',
    name:   'Plate Greaves II',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/platelegs2.png',
    material: 'plate',
  },
  platelegs3: {
    id:     'platelegs3',
    name:   'Plate Greaves III',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/platelegs3.png',
    material: 'plate',
  },
  platelegs4: {
    id:     'platelegs4',
    name:   'Plate Greaves IV',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/platelegs4.png',
    material: 'plate',
  },

  clothlegs1: {
    id:     'clothlegs1',
    name:   'Cloth Trousers',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs1.png',
    material: 'cloth',
  },
  clothlegs2: {
    id:     'clothlegs2',
    name:   'Cloth Trousers II',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs2.png',
    material: 'cloth',
  },
  clothlegs3: {
    id:     'clothlegs3',
    name:   'Cloth Trousers III',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs3.png',
    material: 'cloth',
  },
  clothlegs4: {
    id:     'clothlegs4',
    name:   'Cloth Trousers IV',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs4.png',
    material: 'cloth',
  },
  clothlegs5: {
    id:     'clothlegs5',
    name:   'Cloth Trousers V',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs5.png',
    material: 'cloth',
  },
  clothlegs6: {
    id:     'clothlegs6',
    name:   'Cloth Trousers VI',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs6.png',
    material: 'cloth',
  },
  clothlegs7: {
    id:     'clothlegs7',
    name:   'Cloth Trousers VII',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs7.png',
    material: 'cloth',
  },
  clothlegs8: {
    id:     'clothlegs8',
    name:   'Cloth Trousers VIII',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs8.png',
    material: 'cloth',
  },
  clothlegs9: {
    id:     'clothlegs9',
    name:   'Cloth Trousers IX',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs9.png',
    material: 'cloth',
  },
  clothlegs10: {
    id:     'clothlegs10',
    name:   'Cloth Trousers X',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs10.png',
    material: 'cloth',
  },
  clothlegs11: {
    id:     'clothlegs11',
    name:   'Cloth Trousers XI',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/clothlegs11.png',
    material: 'cloth',
  },

  loincloth1: {
    id:     'loincloth1',
    name:   'Simple Loincloth',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/loincloth1.png',
    material: 'cloth',
  },
  loincloth2: {
    id:     'loincloth2',
    name:   'Simple Loincloth II',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/loincloth2.png',
    material: 'cloth',
  },
  loincloth3: {
    id:     'loincloth3',
    name:   'Simple Loincloth III',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/loincloth3.png',
    material: 'cloth',
  },

  leatherhelm1: {
    id:     'leatherhelm1',
    name:   'Leather Helm',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm1.png',
    material: 'leather',
  },
  leatherhelm2: {
    id:     'leatherhelm2',
    name:   'Leather Helm II',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm2.png',
    material: 'leather',
  },
  leatherhelm3: {
    id:     'leatherhelm3',
    name:   'Leather Helm III',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm3.png',
    material: 'leather',
  },
  leatherhelm4: {
    id:     'leatherhelm4',
    name:   'Leather Helm IV',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm4.png',
    material: 'leather',
  },
  leatherhelm5: {
    id:     'leatherhelm5',
    name:   'Leather Helm V',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm5.png',
    material: 'leather',
  },
  leatherhelm6: {
    id:     'leatherhelm6',
    name:   'Leather Helm VI',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm6.png',
    material: 'leather',
  },
  leatherhelm7: {
    id:     'leatherhelm7',
    name:   'Leather Helm VII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm7.png',
    material: 'leather',
  },
  leatherhelm8: {
    id:     'leatherhelm8',
    name:   'Leather Helm VIII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm8.png',
    material: 'leather',
  },
  leatherhelm9: {
    id:     'leatherhelm9',
    name:   'Leather Helm IX',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherhelm9.png',
    material: 'leather',
  },

  platehelm1: {
    id:     'platehelm1',
    name:   'Plate Helm',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm1.png',
    material: 'plate',
  },
  platehelm2: {
    id:     'platehelm2',
    name:   'Plate Helm II',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm2.png',
    material: 'plate',
  },
  platehelm3: {
    id:     'platehelm3',
    name:   'Plate Helm III',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm3.png',
    material: 'plate',
  },
  platehelm4: {
    id:     'platehelm4',
    name:   'Plate Helm IV',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm4.png',
    material: 'plate',
  },
  platehelm5: {
    id:     'platehelm5',
    name:   'Plate Helm V',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm5.png',
    material: 'plate',
  },
  platehelm6: {
    id:     'platehelm6',
    name:   'Plate Helm VI',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm6.png',
    material: 'plate',
  },
  platehelm7: {
    id:     'platehelm7',
    name:   'Plate Helm VII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm7.png',
    material: 'plate',
  },
  platehelm8: {
    id:     'platehelm8',
    name:   'Plate Helm VIII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm8.png',
    material: 'plate',
  },
  platehelm9: {
    id:     'platehelm9',
    name:   'Plate Helm IX',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm9.png',
    material: 'plate',
  },
  platehelm10: {
    id:     'platehelm10',
    name:   'Plate Helm X',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm10.png',
    material: 'plate',
  },
  platehelm11: {
    id:     'platehelm11',
    name:   'Plate Helm XI',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm11.png',
    material: 'plate',
  },
  platehelm12: {
    id:     'platehelm12',
    name:   'Plate Helm XII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm12.png',
    material: 'plate',
  },
  platehelm13: {
    id:     'platehelm13',
    name:   'Plate Helm XIII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/platehelm13.png',
    material: 'plate',
  },

  crown1: {
    id:     'crown1',
    name:   'Crown',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown1.png',
    material: 'cloth',
  },
  crown2: {
    id:     'crown2',
    name:   'Crown II',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown2.png',
    material: 'cloth',
  },
  crown3: {
    id:     'crown3',
    name:   'Crown III',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown3.png',
    material: 'cloth',
  },
  crown4: {
    id:     'crown4',
    name:   'Crown IV',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown4.png',
    material: 'cloth',
  },
  crown5: {
    id:     'crown5',
    name:   'Crown V',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown5.png',
    material: 'cloth',
  },
  crown6: {
    id:     'crown6',
    name:   'Crown VI',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown6.png',
    material: 'cloth',
  },
  crown7: {
    id:     'crown7',
    name:   'Crown VII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown7.png',
    material: 'cloth',
  },
  crown8: {
    id:     'crown8',
    name:   'Crown VIII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown8.png',
    material: 'cloth',
  },
  crown9: {
    id:     'crown9',
    name:   'Crown IX',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown9.png',
    material: 'cloth',
  },
  crown10: {
    id:     'crown10',
    name:   'Crown X',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown10.png',
    material: 'cloth',
  },
  crown11: {
    id:     'crown11',
    name:   'Crown XI',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown11.png',
    material: 'cloth',
  },
  crown12: {
    id:     'crown12',
    name:   'Crown XII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown12.png',
    material: 'cloth',
  },
  crown13: {
    id:     'crown13',
    name:   'Crown XIII',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown13.png',
    material: 'cloth',
  },
  crown14: {
    id:     'crown14',
    name:   'Crown XIV',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown14.png',
    material: 'cloth',
  },
  crown15: {
    id:     'crown15',
    name:   'Crown XV',
    slot:   'head',
    rarity: 'grey',
    icon:   'assets/items/armor/crown15.png',
    material: 'cloth',
  },

  // ⚠ material 'cloth' on a scale/studded belt is deliberate, not a mistake. A belt ISN'T
  // armor — it's a strap — so it needs no proficiency and anyone can wear it, Rasec included
  // (user's call, 2026-07-17). `cloth` IS the no-proficiency bucket; the NAME carries the
  // flavour. Only plate/chain belts stay gated, because those are actual plate.
  scalebelt: {
    id:     'scalebelt',
    name:   'Scale Belt',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/scalebelt.png',
    material: 'cloth',
  },
  studdedbelt: {
    id:     'studdedbelt',
    name:   'Studded Belt',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/studdedbelt.png',
    material: 'cloth',
  },
  platebelt6: {
    id:     'platebelt6',
    name:   'Plate Belt VI',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/platebelt6.png',
    material: 'plate',
  },
  chainbelt3: {
    id:     'chainbelt3',
    name:   'Chain Belt III',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/chainbelt3.png',
    material: 'plate',
  },
  platebelt5: {
    id:     'platebelt5',
    name:   'Plate Belt V',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/platebelt5.png',
    material: 'plate',
  },
  platebelt4: {
    id:     'platebelt4',
    name:   'Plate Belt IV',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/platebelt4.png',
    material: 'plate',
  },
  platebelt: {
    id:     'platebelt',
    name:   'Plate Belt',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/platebelt.png',
    material: 'plate',
  },
  belt8: {
    id:     'belt8',
    name:   'Simple Belt',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt8.png',
    material: 'cloth',
  },
  platebelt3: {
    id:     'platebelt3',
    name:   'Plate Belt III',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/platebelt3.png',
    material: 'plate',
  },
  chainbelt: {
    id:     'chainbelt',
    name:   'Chain Belt',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/chainbelt.png',
    material: 'plate',
  },
  chainbelt2: {
    id:     'chainbelt2',
    name:   'Chain Belt II',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/chainbelt2.png',
    material: 'plate',
  },
  platebelt2: {
    id:     'platebelt2',
    name:   'Plate Belt II',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/platebelt2.png',
    material: 'plate',
  },
  belt13: {
    id:     'belt13',
    name:   'Simple Belt',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt13.png',
    material: 'cloth',
  },
  belt14: {
    id:     'belt14',
    name:   'Belt XIV',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt14.png',
    material: 'cloth',
  },
  belt15: {
    id:     'belt15',
    name:   'Belt XV',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt15.png',
    material: 'cloth',
  },
  belt16: {
    id:     'belt16',
    name:   'Belt XVI',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt16.png',
    material: 'cloth',
  },
  belt17: {
    id:     'belt17',
    name:   'Belt XVII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt17.png',
    material: 'cloth',
  },
  belt18: {
    id:     'belt18',
    name:   'Belt XVIII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt18.png',
    material: 'cloth',
  },
  belt19: {
    id:     'belt19',
    name:   'Belt XIX',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt19.png',
    material: 'cloth',
  },

  necklace1: {
    id:     'necklace1',
    name:   'Necklace',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace1.png',
  },
  necklace2: {
    id:     'necklace2',
    name:   'Necklace II',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace2.png',
  },
  necklace3: {
    id:     'necklace3',
    name:   'Necklace III',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace3.png',
  },
  necklace4: {
    id:     'necklace4',
    name:   'Necklace IV',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace4.png',
  },
  necklace5: {
    id:     'necklace5',
    name:   'Necklace V',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace5.png',
  },
  necklace6: {
    id:     'necklace6',
    name:   'Necklace VI',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace6.png',
  },
  necklace7: {
    id:     'necklace7',
    name:   'Necklace VII',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace7.png',
  },
  necklace8: {
    id:     'necklace8',
    name:   'Necklace VIII',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace8.png',
  },
  necklace9: {
    id:     'necklace9',
    name:   'Necklace IX',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace9.png',
  },
  necklace10: {
    id:     'necklace10',
    name:   'Necklace X',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace10.png',
  },
  soul_shard_amulet: {
    id:     'soul_shard_amulet',
    name:   'Soul Shard Amulet',
    slot:   'neck',
    rarity: 'green',
    icon:   'assets/items/jewelry/necklace10.png',
    // Scripted one-off (Morvath, once ever — see loot.js). noDrop keeps it OUT of the random
    // drop pool: it has a bespoke effect and a fixed rarity, so a goblin coughing one up
    // would both cheapen it and hand out a green at a CR that can't roll one.
    noDrop: true,
    undeadReactionHeal: '1d4',
    description: "When you kill an undead creature, you may use your reaction to absorb a tiny fragment of its undead life force and regain 1d4 hit points.",
  },
  // ── On-hit rider amulets ─────────────────────────────────────────────────────
  // Each locks ONE elemental damage rider via signatureAffix (see js/affixes.js neck table):
  // on a hit the wearer sears the target for the tier's dice, and the target's save halves it.
  // `rarity` here is just the base's default; a drop overwrites it (loot.js _rollItem), so these
  // scale green→red like any rolled item, the rider damage climbing with the tier.
  emberheart_pendant: {
    id:     'emberheart_pendant',
    name:   'Emberheart Pendant',
    slot:   'neck',
    rarity: 'green',
    icon:   'assets/items/jewelry/necklace2.png',
    signatureAffix: 'rider_fire',
    description: 'Your strikes carry a searing ember. On a hit the target takes fire damage — a Dexterity save halves it.',
  },
  rimefrost_locket: {
    id:     'rimefrost_locket',
    name:   'Rimefrost Locket',
    slot:   'neck',
    rarity: 'green',
    icon:   'assets/items/jewelry/necklace3.png',
    signatureAffix: 'rider_ice',
    description: 'Your strikes bite with sudden cold. On a hit the target takes cold damage — a Constitution save halves it.',
  },
  viperfang_amulet: {
    id:     'viperfang_amulet',
    name:   'Viperfang Amulet',
    slot:   'neck',
    rarity: 'green',
    icon:   'assets/items/jewelry/necklace4.png',
    signatureAffix: 'rider_poison',
    description: 'Your strikes drip venom. On a hit the target takes poison damage — a Constitution save halves it.',
  },
  plaguewrought_charm: {
    id:     'plaguewrought_charm',
    name:   'Plaguewrought Charm',
    slot:   'neck',
    rarity: 'green',
    icon:   'assets/items/jewelry/necklace7.png',
    signatureAffix: 'rider_disease',
    description: 'Your strikes fester with sickness. On a hit the target takes disease damage — a Constitution save halves it.',
  },
  necklace11: {
    id:     'necklace11',
    name:   'Necklace XI',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace11.png',
  },

  clothshirt1: {
    id:     'clothshirt1',
    name:   'Cloth Shirt',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt1.png',
    ac:     0,
    material: 'cloth',
  },
  clothshirt2: {
    id:     'clothshirt2',
    name:   'Cloth Shirt II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt2.png',
    ac:     0,
    material: 'cloth',
  },
  clothshirt3: {
    id:     'clothshirt3',
    name:   'Cloth Shirt III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt3.png',
    ac:     0,
    material: 'cloth',
  },
  clothshirt4: {
    id:     'clothshirt4',
    name:   'Cloth Shirt IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt4.png',
    ac:     0,
    material: 'cloth',
  },
  clothshirt5: {
    id:     'clothshirt5',
    name:   'Cloth Shirt V',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt5.png',
    ac:     0,
    material: 'cloth',
  },
  clothshirt6: {
    id:     'clothshirt6',
    name:   'Cloth Shirt VI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt6.png',
    ac:     0,
    material: 'cloth',
  },
  clothshirt7: {
    id:     'clothshirt7',
    name:   'Cloth Shirt VII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt7.png',
    ac:     0,
    material: 'cloth',
  },
  clothshirt8: {
    id:     'clothshirt8',
    name:   'Cloth Shirt VIII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/clothshirt8.png',
    ac:     0,
    material: 'cloth',
  },

  robe1: {
    id:     'robe1',
    name:   'Robe',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe1.png',
    material: 'cloth',
  },
  robe2: {
    id:     'robe2',
    name:   'Simple Robe',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe2.png',
    material: 'cloth',
  },
  robe3: {
    id:     'robe3',
    name:   'Robe III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe3.png',
    material: 'cloth',
  },
  robe4: {
    id:     'robe4',
    name:   'Robe IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe4.png',
    material: 'cloth',
  },
  robe5: {
    id:     'robe5',
    name:   'Robe V',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe5.png',
    material: 'cloth',
  },
  robe6: {
    id:     'robe6',
    name:   'Robe VI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe6.png',
    material: 'cloth',
  },
  robe7: {
    id:     'robe7',
    name:   'Robe VII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe7.png',
    material: 'cloth',
  },
  robe8: {
    id:     'robe8',
    name:   'Robe VIII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe8.png',
    material: 'cloth',
  },
  robe9: {
    id:     'robe9',
    name:   'Robe IX',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe9.png',
    material: 'cloth',
  },
  robe10: {
    id:     'robe10',
    name:   'Robe X',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe10.png',
    material: 'cloth',
  },
  robe11: {
    id:     'robe11',
    name:   'Robe XI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe11.png',
    material: 'cloth',
  },

  glvoes1: {
    id:     'glvoes1',
    name:   'Gloves',
    slot:   'hands',
    rarity: 'grey',
    // Was 'glvoes1.png' — a typo'd path with no file behind it, so this rendered as a
    // broken image. It was the ONLY dead icon reference of the 373. No plain "gloves" art
    // exists, so it reuses the cloth set; the id keeps its spelling to avoid breaking any
    // saved bag that already holds one.
    icon:   'assets/items/armor/clothgloves1.png',
    material: 'cloth',
  },
  clothgloves1: {
    id:     'clothgloves1',
    name:   'Cloth Gloves',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves1.png',
    material: 'cloth',
  },
  clothgloves2: {
    id:     'clothgloves2',
    name:   'Cloth Gloves II',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves2.png',
    material: 'cloth',
  },
  clothgloves3: {
    id:     'clothgloves3',
    name:   'Cloth Gloves III',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves3.png',
    material: 'cloth',
  },
  clothgloves4: {
    id:     'clothgloves4',
    name:   'Cloth Gloves IV',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves4.png',
    material: 'cloth',
  },
  clothgloves5: {
    id:     'clothgloves5',
    name:   'Cloth Gloves V',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves5.png',
    material: 'cloth',
  },
  clothgloves6: {
    id:     'clothgloves6',
    name:   'Cloth Gloves VI',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves6.png',
    material: 'cloth',
  },
  clothgloves7: {
    id:     'clothgloves7',
    name:   'Cloth Gloves VII',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves7.png',
    material: 'cloth',
  },
  clothgloves8: {
    id:     'clothgloves8',
    name:   'Cloth Gloves VIII',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves8.png',
    material: 'cloth',
  },
  clothgloves9: {
    id:     'clothgloves9',
    name:   'Cloth Gloves IX',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/clothgloves9.png',
    material: 'cloth',
  },

  wrist1: {
    id:     'wrist1',
    name:   'Bracer',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist1.png',
    material: 'cloth',
  },
  wrist2: {
    id:     'wrist2',
    name:   'Bracer II',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist2.png',
    material: 'cloth',
  },
  wrist3: {
    id:     'wrist3',
    name:   'Bracer III',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist3.png',
    material: 'cloth',
  },
  wrist4: {
    id:     'wrist4',
    name:   'Bracer IV',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist4.png',
    material: 'cloth',
  },
  wrist5: {
    id:     'wrist5',
    name:   'Bracer V',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist5.png',
    material: 'cloth',
  },
  wrist6: {
    id:     'wrist6',
    name:   'Bracer VI',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist6.png',
    material: 'cloth',
  },
  wrist7: {
    id:     'wrist7',
    name:   'Bracer VII',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist7.png',
    material: 'cloth',
  },
  wrist8: {
    id:     'wrist8',
    name:   'Bracer VIII',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist8.png',
    material: 'cloth',
  },
  wrist9: {
    id:     'wrist9',
    name:   'Bracer IX',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist9.png',
    material: 'cloth',
  },
  wrist10: {
    id:     'wrist10',
    name:   'Bracer X',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist10.png',
    material: 'cloth',
  },
  wrist11: {
    id:     'wrist11',
    name:   'Bracer XI',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist11.png',
    material: 'cloth',
  },
  wrist12: {
    id:     'wrist12',
    name:   'Bracer XII',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist12.png',
    material: 'cloth',
  },

  ring1: {
    id:     'ring1',
    name:   'Ring',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring1.png',
  },
  ring2: {
    id:     'ring2',
    name:   'Ring II',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring2.png',
  },
  ring3: {
    id:     'ring3',
    name:   'Ring III',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring3.png',
  },
  ring4: {
    id:     'ring4',
    name:   'Ring IV',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring4.png',
  },
  ring5: {
    id:     'ring5',
    name:   'Ring V',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring5.png',
  },
  ring6: {
    id:     'ring6',
    name:   'Ring VI',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring6.png',
  },
  ring7: {
    id:     'ring7',
    name:   'Ring VII',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring7.png',
  },
  ring8: {
    id:     'ring8',
    name:   'Ring VIII',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring8.png',
  },
  ring9: {
    id:     'ring9',
    name:   'Ring IX',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring9.png',
  },
  ring10: {
    id:     'ring10',
    name:   'Ring X',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring10.png',
  },
  ring11: {
    id:     'ring11',
    name:   'Ring XI',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring11.png',
  },
  ring12: {
    id:     'ring12',
    name:   'Ring XII',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring12.png',
  },
  ring13: {
    id:     'ring13',
    name:   'Ring XIII',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring13.png',
  },
  ring14: {
    id:     'ring14',
    name:   'Ring XIV',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring14.png',
  },
  ring15: {
    id:     'ring15',
    name:   'Ring XV',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring15.png',
  },

  leatherboots1: {
    id:     'leatherboots1',
    name:   'Leather Boots',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots1.png',
    material: 'leather',
  },
  leatherboots2: {
    id:     'leatherboots2',
    name:   'Simple Leather Boots',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots2.png',
    material: 'leather',
  },
  leatherboots3: {
    id:     'leatherboots3',
    name:   'Leather Boots III',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots3.png',
    material: 'leather',
  },
  leatherboots4: {
    id:     'leatherboots4',
    name:   'Leather Boots IV',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots4.png',
    material: 'leather',
  },
  leatherboots5: {
    id:     'leatherboots5',
    name:   'Leather Boots V',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots5.png',
    material: 'leather',
  },
  leatherboots6: {
    id:     'leatherboots6',
    name:   'Leather Boots VI',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots6.png',
    material: 'leather',
  },
  leatherboots7: {
    id:     'leatherboots7',
    name:   'Leather Boots VII',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherboots7.png',
    material: 'leather',
  },
  sandals1: {
    id:     'sandals1',
    name:   'Sandals',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals1.png',
    material: 'cloth',
  },
  sandals2: {
    id:     'sandals2',
    name:   'Sandals II',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals2.png',
    material: 'cloth',
  },
  sandals3: {
    id:     'sandals3',
    name:   'Sandals III',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals3.png',
    material: 'cloth',
  },
  sandals4: {
    id:     'sandals4',
    name:   'Sandals IV',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals4.png',
    material: 'cloth',
  },
  sandals5: {
    id:     'sandals5',
    name:   'Sandals V',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals5.png',
    material: 'cloth',
  },
  sandals6: {
    id:     'sandals6',
    name:   'Simple Sandals',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals6.png',
    material: 'cloth',
  },
  sandals7: {
    id:     'sandals7',
    name:   'Sandals VII',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals7.png',
    material: 'cloth',
  },
  sandals8: {
    id:     'sandals8',
    name:   'Sandals VIII',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals8.png',
    material: 'cloth',
  },
  sandals9: {
    id:     'sandals9',
    name:   'Sandals IX',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/sandals9.png',
    material: 'cloth',
  },
  mixedboots1: {
    id:     'mixedboots1',
    name:   'Mixed Boots',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedboots1.png',
    material: 'hide',
  },
  mixedboots2: {
    id:     'mixedboots2',
    name:   'Mixed Boots II',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedboots2.png',
    material: 'hide',
  },
  mixedboots3: {
    id:     'mixedboots3',
    name:   'Mixed Boots III',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedboots3.png',
    material: 'hide',
  },
  plateboots1: {
    id:     'plateboots1',
    name:   'Plate Boots',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots1.png',
    material: 'plate',
  },
  plateboots2: {
    id:     'plateboots2',
    name:   'Plate Boots II',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots2.png',
    material: 'plate',
  },
  plateboots3: {
    id:     'plateboots3',
    name:   'Plate Boots III',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots3.png',
    material: 'plate',
  },
  plateboots4: {
    id:     'plateboots4',
    name:   'Simple Mail Boots',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots4.png',
    material: 'plate',
  },
  plateboots5: {
    id:     'plateboots5',
    name:   'Plate Boots V',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots5.png',
    material: 'plate',
  },
  plateboots6: {
    id:     'plateboots6',
    name:   'Plate Boots VI',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots6.png',
    material: 'plate',
  },
  plateboots7: {
    id:     'plateboots7',
    name:   'Plate Boots VII',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots7.png',
    material: 'plate',
  },
  plateboots8: {
    id:     'plateboots8',
    name:   'Plate Boots VIII',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots8.png',
    material: 'plate',
  },
  plateboots9: {
    id:     'plateboots9',
    name:   'Plate Boots IX',
    slot:   'feet',
    rarity: 'grey',
    icon:   'assets/items/armor/plateboots9.png',
    material: 'plate',
  },

  mixedgloves1: {
    id:     'mixedgloves1',
    name:   'Mixed Gloves',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedgloves1.png',
    material: 'hide',
  },
  mixedgloves2: {
    id:     'mixedgloves2',
    name:   'Mixed Gloves II',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedgloves2.png',
    material: 'hide',
  },
  mixedgloves3: {
    id:     'mixedgloves3',
    name:   'Mixed Gloves III',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedgloves3.png',
    material: 'hide',
  },
  mixedgloves4: {
    id:     'mixedgloves4',
    name:   'Mixed Gloves IV',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedgloves4.png',
    material: 'hide',
  },
  plategloves1: {
    id:     'plategloves1',
    name:   'Plate Gauntlets',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/plategloves1.png',
    material: 'plate',
  },
  plategloves2: {
    id:     'plategloves2',
    name:   'Plate Gauntlets II',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/plategloves2.png',
    material: 'plate',
  },
  plategloves3: {
    id:     'plategloves3',
    name:   'Plate Gauntlets III',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/plategloves3.png',
    material: 'plate',
  },
  plategloves4: {
    id:     'plategloves4',
    name:   'Plate Gauntlets IV',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/plategloves4.png',
    material: 'plate',
  },
  plategloves5: {
    id:     'plategloves5',
    name:   'Plate Gauntlets V',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/plategloves5.png',
    material: 'plate',
  },

  leatherwrist1: {
    id:     'leatherwrist1',
    name:   'Leather Bracer',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherwrist1.png',
    material: 'leather',
  },
  leatherwrist2: {
    id:     'leatherwrist2',
    name:   'Leather Bracer II',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherwrist2.png',
    material: 'leather',
  },
  leatherwrist3: {
    id:     'leatherwrist3',
    name:   'Leather Bracer III',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherwrist3.png',
    material: 'leather',
  },
  leatherwrist5: {
    id:     'leatherwrist5',
    name:   'Leather Bracer V',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherwrist5.png',
    material: 'leather',
  },
  leatherwrist4: {
    id:     'leatherwrist4',
    name:   'Leather Bracer IV',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherwrist4.png',
    material: 'leather',
  },
  platewrist7: {
    id:     'platewrist7',
    name:   'Plate Bracer VII',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist7.png',
    material: 'plate',
  },
  platewrist1: {
    id:     'platewrist1',
    name:   'Plate Bracer',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist1.png',
    material: 'plate',
  },
  platewrist2: {
    id:     'platewrist2',
    name:   'Plate Bracer II',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist2.png',
    material: 'plate',
  },
  platewrist3: {
    id:     'platewrist3',
    name:   'Plate Bracer III',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist3.png',
    material: 'plate',
  },
  platewrist4: {
    id:     'platewrist4',
    name:   'Plate Bracer IV',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist4.png',
    material: 'plate',
  },
  platewrist5: {
    id:     'platewrist5',
    name:   'Plate Bracer V',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist5.png',
    material: 'plate',
  },
  platewrist6: {
    id:     'platewrist6',
    name:   'Plate Bracer VI',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/platewrist6.png',
    material: 'plate',
  },

  cloak1: {
    id:     'cloak1',
    name:   'Cloak',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak1.png',
  },
  cloak2: {
    id:     'cloak2',
    name:   'Cloak II',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak2.png',
  },
  cloak3: {
    id:     'cloak3',
    name:   'Cloak III',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak3.png',
  },
  cloak4: {
    id:     'cloak4',
    name:   'Cloak IV',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak4.png',
  },
  cloak5: {
    id:     'cloak5',
    name:   'Cloak V',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak5.png',
  },
  cloak6: {
    id:     'cloak6',
    name:   'Cloak VI',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak6.png',
  },
  cloak7: {
    id:     'cloak7',
    name:   'Cloak VII',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak7.png',
  },
  cloak8: {
    id:     'cloak8',
    name:   'Cloak VIII',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak8.png',
  },
  cloak9: {
    id:     'cloak9',
    name:   'Cloak IX',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak9.png',
  },
  cloak10: {
    id:     'cloak10',
    name:   'Cloak X',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak10.png',
  },
  cloak11: {
    id:     'cloak11',
    name:   'Cloak XI',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak11.png',
  },
  cloak12: {
    id:     'cloak12',
    name:   'Simple Cloak',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak12.png',
  },
  cloak13: {
    id:     'cloak13',
    name:   'Cloak XIII',
    slot:   'cloak',
    rarity: 'grey',
    icon:   'assets/items/armor/cloak13.png',
  },

  leathergloves1: {
    id:     'leathergloves1',
    name:   'Leather Gloves',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves1.png',
    material: 'leather',
  },
  studdedleathergloves: {
    id:     'studdedleathergloves',
    name:   'Studded Leather Gloves',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/studdedleathergloves.png',
    material: 'leather',   // studded leather is Light armor in the book, same as plain leather
  },
  leathergloves3: {
    id:     'leathergloves3',
    name:   'Leather Gloves III',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves3.png',
    material: 'leather',
  },
  leathergloves4: {
    id:     'leathergloves4',
    name:   'Leather Gloves IV',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves4.png',
    material: 'leather',
  },
  leathergloves5: {
    id:     'leathergloves5',
    name:   'Leather Gloves V',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves5.png',
    material: 'leather',
  },
  leathergloves6: {
    id:     'leathergloves6',
    name:   'Leather Gloves VI',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves6.png',
    material: 'leather',
  },
  leathergloves7: {
    id:     'leathergloves7',
    name:   'Leather Gloves VII',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves7.png',
    material: 'leather',
  },
  leathergloves8: {
    id:     'leathergloves8',
    name:   'Leather Gloves VIII',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/leathergloves8.png',
    material: 'leather',
  },

  // ── Alchemy materials (bag items, not equippable) ──────────────────────────
  grassling_dung: {
    id:          'grassling_dung',
    name:        'Grassling Dung',
    rarity:      'green',
    icon:        'assets/items/materials/grassling dung.png',
    material:    true,
    value:       25,
    description: 'Sacred dung from the grassling mounds. Bring it to an alchemist in the towns of men to render it into 2 Potions of Lesser Healing.',
  },

  // Quest key — dropped by a Warrens goblin jailer; opens Solrac's shackles.
  goblin_key: {
    id:          'goblin_key',
    name:        'Goblin Key',
    rarity:      'green',
    icon:        'assets/items/materials/goblin key.png',
    material:    true,
    value:       0,
    description: "A crude iron key wrenched from a goblin jailer in the Warrens.",
  },
  greataxe4: {
    id:     'greataxe4',
    name:   'Greataxe IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/greataxe4.png',
    dmg:    '1d12',
    dmgType: 'slashing',
    heavy: true,
    twoHanded: true,
    weaponType: 'Greataxe',
    category: 'martial',
  },
  greataxe5: {
    id:     'greataxe5',
    name:   'Greataxe V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/greataxe5.png',
    dmg:    '1d12',
    dmgType: 'slashing',
    heavy: true,
    twoHanded: true,
    weaponType: 'Greataxe',
    category: 'martial',
  },
  arrow1: {
    id:     'arrow1',
    name:   'Arrows',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/arrow1.png',
    weaponType: 'Arrow',
    category: 'simple',
  },
  arrow2: {
    id:     'arrow2',
    name:   'Arrows II',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/arrow2.png',
    weaponType: 'Arrow',
    category: 'simple',
  },
  arrow3: {
    id:     'arrow3',
    name:   'Arrows III',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/arrow3.png',
    weaponType: 'Arrow',
    category: 'simple',
  },
  arrow4: {
    id:     'arrow4',
    name:   'Arrows IV',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/arrow4.png',
    weaponType: 'Arrow',
    category: 'simple',
  },
  dart1: {
    id:     'dart1',
    name:   'Darts',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/dart1.png',
    weaponType: 'Dart',
    dmg:    '1d4',
    dmgType: 'piercing',
    finesse: true,
    thrown: true,
    range:  20,
    longRange: 60,
    category: 'simple',
  },
  dart2: {
    id:     'dart2',
    name:   'Darts II',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/dart2.png',
    weaponType: 'Dart',
    dmg:    '1d4',
    dmgType: 'piercing',
    finesse: true,
    thrown: true,
    range:  20,
    longRange: 60,
    category: 'simple',
  },
  dart3: {
    id:     'dart3',
    name:   'Darts III',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/dart3.png',
    weaponType: 'Dart',
    dmg:    '1d4',
    dmgType: 'piercing',
    finesse: true,
    thrown: true,
    range:  20,
    longRange: 60,
    category: 'simple',
  },
  throwingaxe1: {
    id:     'throwingaxe1',
    name:   'Throwing Axes',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/handaxe.png',
    weaponType: 'Handaxe',
    category: 'simple',
  },
  throwingaxe2: {
    id:     'throwingaxe2',
    name:   'Throwing Axes II',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/handaxe1.png',
    weaponType: 'Handaxe',
    category: 'simple',
  },
  throwingaxe3: {
    id:     'throwingaxe3',
    name:   'Throwing Axes III',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/handaxe2.png',
    weaponType: 'Handaxe',
    category: 'simple',
  },
  throwinghammer1: {
    id:     'throwinghammer1',
    name:   'Throwing Hammers',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/lighthammer1.png',
    weaponType: 'Light Hammer',
    category: 'simple',
  },
  throwinghammer2: {
    id:     'throwinghammer2',
    name:   'Throwing Hammers II',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/lighthammer2.png',
    weaponType: 'Light Hammer',
    category: 'simple',
  },
  throwinghammer3: {
    id:     'throwinghammer3',
    name:   'Throwing Hammers III',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/lighthammer3.png',
    weaponType: 'Light Hammer',
    category: 'simple',
  },
  throwinghammer4: {
    id:     'throwinghammer4',
    name:   'Throwing Hammers IV',
    slot:   'ammo',
    rarity: 'grey',
    icon:   'assets/items/weapons/lighthammer4.png',
    weaponType: 'Light Hammer',
    category: 'simple',
  },
};

// Can the random loot table hand this out? Anything with an equipment slot that isn't a
// scripted one-off. Quest materials (goblin key, grassling dung) carry no `slot` and are
// excluded by that alone; `noDrop` covers the ones that DO have a slot (soul shard amulet).
//
// Shared so loot.js's drop pool and lootCoverage.js's per-material index can't drift apart —
// an item droppable by one and invisible to the other would silently skew the coverage math.
export const isDroppable = it => !!it?.slot && !it.noDrop;

export function getItem(id) {
  const def = ITEMS[id];
  return def ? { ...def } : null;
}
