// js/items.js — equippable item catalog (see js/equipment.js for the item schema)

export const ITEMS = {
  bag1: {
    id:     'bag1',
    name:   'Bag',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag1.png',
  },
  bag2: {
    id:     'bag2',
    name:   'Bag II',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag2.png',
  },
  bag3: {
    id:     'bag3',
    name:   'Bag III',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag3.png',
  },
  bag4: {
    id:     'bag4',
    name:   'Bag IV',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag4.png',
  },
  bag5: {
    id:     'bag5',
    name:   'Bag V',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag5.png',
  },
  bag6: {
    id:     'bag6',
    name:   'Bag VI',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag6.png',
  },
  bag7: {
    id:     'bag7',
    name:   'Bag VII',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag7.png',
  },
  bag8: {
    id:     'bag8',
    name:   'Bag VIII',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag8.png',
  },
  bag9: {
    id:     'bag9',
    name:   'Bag IX',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag9.png',
  },
  bag10: {
    id:     'bag10',
    name:   'Bag X',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag10.png',
  },
  bag11: {
    id:     'bag11',
    name:   'Bag XI',
    slot:   'bag',
    rarity: 'grey',
    icon:   'assets/items/bags/bag11.png',
  },

  handaxe: {
    id:     'handaxe',
    name:   'Handaxe',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/handaxe.png',
    dmg:    '1d6',
    dmgType: 'slashing',
  },
  battleaxe: {
    id:     'battleaxe',
    name:   'Battleaxe',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/battleaxe.png',
    dmg:    '1d8',
    dmgType: 'slashing',
  },
  greataxe: {
    id:     'greataxe',
    name:   'Greataxe',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/greataxe.png',
    dmg:    '1d12',
    dmgType: 'slashing',
  },

  warhammer1: {
    id:     'warhammer1',
    name:   'Warhammer',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer1.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
  },
  warhammer2: {
    id:     'warhammer2',
    name:   'Warhammer II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer2.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
  },
  warhammer3: {
    id:     'warhammer3',
    name:   'Warhammer III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer3.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
  },
  warhammer4: {
    id:     'warhammer4',
    name:   'Warhammer IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer4.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
  },
  warhammer5: {
    id:     'warhammer5',
    name:   'Warhammer V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer5.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
  },
  warhammer6: {
    id:     'warhammer6',
    name:   'Warhammer VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer6.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
  },
  warhammer7: {
    id:     'warhammer7',
    name:   'Warhammer VII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer7.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
  },
  warhammer8: {
    id:     'warhammer8',
    name:   'Warhammer VIII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer8.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
  },
  warhammer9: {
    id:     'warhammer9',
    name:   'Warhammer IX',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer9.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
  },
  warhammer10: {
    id:     'warhammer10',
    name:   'Warhammer X',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/warhammer10.png',
    dmg:    '1d8',
    dmgType: 'bludgeoning',
  },

  sword1: {
    id:     'sword1',
    name:   'Sword',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword1.png',
    dmg:    '1d8',
    dmgType: 'slashing',
  },
  sword2: {
    id:     'sword2',
    name:   'Sword II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword2.png',
    dmg:    '1d8',
    dmgType: 'slashing',
  },
  sword3: {
    id:     'sword3',
    name:   'Sword III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword3.png',
    dmg:    '1d8',
    dmgType: 'slashing',
  },
  sword4: {
    id:     'sword4',
    name:   'Sword IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword4.png',
    dmg:    '1d8',
    dmgType: 'slashing',
  },
  sword5: {
    id:     'sword5',
    name:   'Sword V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword5.png',
    dmg:    '1d8',
    dmgType: 'slashing',
  },
  sword6: {
    id:     'sword6',
    name:   'Sword VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword6.png',
    dmg:    '1d8',
    dmgType: 'slashing',
  },
  sword7: {
    id:     'sword7',
    name:   'Sword VII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword7.png',
    dmg:    '1d8',
    dmgType: 'slashing',
  },
  sword8: {
    id:     'sword8',
    name:   'Sword VIII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/sword8.png',
    dmg:    '1d8',
    dmgType: 'slashing',
  },

  stave1: {
    id:     'stave1',
    name:   'Staff',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave1.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
  },
  stave2: {
    id:     'stave2',
    name:   'Staff II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave2.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
  },
  stave3: {
    id:     'stave3',
    name:   'Staff III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave3.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
  },
  stave4: {
    id:     'stave4',
    name:   'Staff IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave4.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
  },
  stave5: {
    id:     'stave5',
    name:   'Staff V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave5.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
  },
  stave6: {
    id:     'stave6',
    name:   'Staff VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave6.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
  },
  stave7: {
    id:     'stave7',
    name:   'Staff VII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave7.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
  },
  stave8: {
    id:     'stave8',
    name:   'Staff VIII',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/stave8.png',
    dmg:    '1d6',
    dmgType: 'bludgeoning',
  },

  wand1: {
    id:     'wand1',
    name:   'Wand',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand1.png',
  },
  wand2: {
    id:     'wand2',
    name:   'Wand II',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand2.png',
  },
  wand3: {
    id:     'wand3',
    name:   'Wand III',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand3.png',
  },
  wand4: {
    id:     'wand4',
    name:   'Wand IV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand4.png',
  },
  wand5: {
    id:     'wand5',
    name:   'Wand V',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand5.png',
  },
  wand6: {
    id:     'wand6',
    name:   'Wand VI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand6.png',
  },
  wand7: {
    id:     'wand7',
    name:   'Wand VII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand7.png',
  },
  wand8: {
    id:     'wand8',
    name:   'Wand VIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand8.png',
  },
  wand9: {
    id:     'wand9',
    name:   'Wand IX',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand9.png',
  },
  wand10: {
    id:     'wand10',
    name:   'Wand X',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand10.png',
  },
  wand11: {
    id:     'wand11',
    name:   'Wand XI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand11.png',
  },
  wand12: {
    id:     'wand12',
    name:   'Wand XII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/wand12.png',
  },

  orb1: {
    id:     'orb1',
    name:   'Orb',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb1.png',
  },
  orb2: {
    id:     'orb2',
    name:   'Orb II',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb2.png',
  },
  orb3: {
    id:     'orb3',
    name:   'Orb III',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb3.png',
  },
  orb4: {
    id:     'orb4',
    name:   'Orb IV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb4.png',
  },
  orb5: {
    id:     'orb5',
    name:   'Orb V',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb5.png',
  },
  orb6: {
    id:     'orb6',
    name:   'Orb VI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb6.png',
  },
  orb7: {
    id:     'orb7',
    name:   'Orb VII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb7.png',
  },
  orb8: {
    id:     'orb8',
    name:   'Orb VIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb8.png',
  },
  orb9: {
    id:     'orb9',
    name:   'Orb IX',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb9.png',
  },
  orb10: {
    id:     'orb10',
    name:   'Orb X',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb10.png',
  },
  orb11: {
    id:     'orb11',
    name:   'Orb XI',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb11.png',
  },
  orb12: {
    id:     'orb12',
    name:   'Orb XII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb12.png',
  },
  orb13: {
    id:     'orb13',
    name:   'Orb XIII',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb13.png',
  },
  orb14: {
    id:     'orb14',
    name:   'Orb XIV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb14.png',
  },
  orb15: {
    id:     'orb15',
    name:   'Orb XV',
    slot:   'off-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/orb15.png',
  },

  dagger1: {
    id:     'dagger1',
    name:   'Dagger',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger1.png',
    dmg:    '1d4',
    dmgType: 'piercing',
  },
  dagger2: {
    id:     'dagger2',
    name:   'Dagger II',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger2.png',
    dmg:    '1d4',
    dmgType: 'piercing',
  },
  dagger3: {
    id:     'dagger3',
    name:   'Dagger III',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger3.png',
    dmg:    '1d4',
    dmgType: 'piercing',
  },
  dagger4: {
    id:     'dagger4',
    name:   'Dagger IV',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger4.png',
    dmg:    '1d4',
    dmgType: 'piercing',
  },
  dagger5: {
    id:     'dagger5',
    name:   'Dagger V',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger5.png',
    dmg:    '1d4',
    dmgType: 'piercing',
  },
  dagger6: {
    id:     'dagger6',
    name:   'Dagger VI',
    slot:   'main-hand',
    rarity: 'grey',
    icon:   'assets/items/weapons/dagger6.png',
    dmg:    '1d4',
    dmgType: 'piercing',
  },

  leatherarmor1: {
    id:     'leatherarmor1',
    name:   'Leather Armor',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor1.png',
    ac:     11,
  },
  leatherarmor2: {
    id:     'leatherarmor2',
    name:   'Leather Armor II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor2.png',
    ac:     11,
  },
  leatherarmor3: {
    id:     'leatherarmor3',
    name:   'Leather Armor III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor3.png',
    ac:     11,
  },
  leatherarmor4: {
    id:     'leatherarmor4',
    name:   'Leather Armor IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor4.png',
    ac:     11,
  },
  leatherarmor5: {
    id:     'leatherarmor5',
    name:   'Leather Armor V',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor5.png',
    ac:     11,
  },
  leatherarmor6: {
    id:     'leatherarmor6',
    name:   'Leather Armor VI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor6.png',
    ac:     11,
  },
  leatherarmor7: {
    id:     'leatherarmor7',
    name:   'Leather Armor VII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor7.png',
    ac:     11,
  },
  leatherarmor8: {
    id:     'leatherarmor8',
    name:   'Leather Armor VIII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor8.png',
    ac:     11,
  },
  leatherarmor9: {
    id:     'leatherarmor9',
    name:   'Leather Armor IX',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor9.png',
    ac:     11,
  },
  leatherarmor10: {
    id:     'leatherarmor10',
    name:   'Leather Armor X',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor10.png',
    ac:     11,
  },
  leatherarmor11: {
    id:     'leatherarmor11',
    name:   'Leather Armor XI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor11.png',
    ac:     11,
  },
  leatherarmor12: {
    id:     'leatherarmor12',
    name:   'Leather Armor XII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor12.png',
    ac:     11,
  },
  leatherarmor13: {
    id:     'leatherarmor13',
    name:   'Leather Armor XIII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor13.png',
    ac:     11,
  },
  leatherarmor14: {
    id:     'leatherarmor14',
    name:   'Leather Armor XIV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor14.png',
    ac:     11,
  },
  leatherarmor15: {
    id:     'leatherarmor15',
    name:   'Leather Armor XV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor15.png',
    ac:     11,
  },
  leatherarmor16: {
    id:     'leatherarmor16',
    name:   'Leather Armor XVI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherarmor16.png',
    ac:     11,
  },

  hidearmor1: {
    id:     'hidearmor1',
    name:   'Hide Armor',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/hidearmor1.png',
    ac:     12,
  },
  hidearmor2: {
    id:     'hidearmor2',
    name:   'Hide Armor II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/hidearmor2.png',
    ac:     12,
  },
  bronzearmor: {
    id:     'bronzearmor',
    name:   'Breastplate',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/bronzearmor.png',
    ac:     14,
  },
  platearmor1: {
    id:     'platearmor1',
    name:   'Plate Armor',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/platearmor1.png',
    ac:     18,
  },
  platearmor2: {
    id:     'platearmor2',
    name:   'Plate Armor II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/platearmor2.png',
    ac:     18,
  },
  platearmor3: {
    id:     'platearmor3',
    name:   'Plate Armor III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/platearmor3.png',
    ac:     18,
  },

  leatherlegs1: {
    id:     'leatherlegs1',
    name:   'Leather Leggings',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs1.png',
    ac:     1,
  },
  leatherlegs2: {
    id:     'leatherlegs2',
    name:   'Leather Leggings II',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs2.png',
    ac:     1,
  },
  leatherlegs3: {
    id:     'leatherlegs3',
    name:   'Leather Leggings III',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs3.png',
    ac:     1,
  },
  leatherlegs4: {
    id:     'leatherlegs4',
    name:   'Leather Leggings IV',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/leatherlegs4.png',
    ac:     1,
  },
  mixedlegs1: {
    id:     'mixedlegs1',
    name:   'Mixed Leggings',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedlegs1.png',
    ac:     2,
  },
  mixedlegs2: {
    id:     'mixedlegs2',
    name:   'Mixed Leggings II',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/mixedlegs2.png',
    ac:     2,
  },
  platelegs1: {
    id:     'platelegs1',
    name:   'Plate Greaves',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/platelegs1.png',
    ac:     3,
  },
  platelegs2: {
    id:     'platelegs2',
    name:   'Plate Greaves II',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/platelegs2.png',
    ac:     3,
  },
  platelegs3: {
    id:     'platelegs3',
    name:   'Plate Greaves III',
    slot:   'legs',
    rarity: 'grey',
    icon:   'assets/items/armor/platelegs3.png',
    ac:     3,
  },

  belt1: {
    id:     'belt1',
    name:   'Belt',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt1.png',
  },
  belt2: {
    id:     'belt2',
    name:   'Belt II',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt2.png',
  },
  belt3: {
    id:     'belt3',
    name:   'Belt III',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt3.png',
  },
  belt4: {
    id:     'belt4',
    name:   'Belt IV',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt4.png',
  },
  belt5: {
    id:     'belt5',
    name:   'Belt V',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt5.png',
  },
  belt6: {
    id:     'belt6',
    name:   'Belt VI',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt6.png',
  },
  belt7: {
    id:     'belt7',
    name:   'Belt VII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt7.png',
  },
  belt8: {
    id:     'belt8',
    name:   'Belt VIII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt8.png',
  },
  belt9: {
    id:     'belt9',
    name:   'Belt IX',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt9.png',
  },
  belt10: {
    id:     'belt10',
    name:   'Belt X',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt10.png',
  },
  belt11: {
    id:     'belt11',
    name:   'Belt XI',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt11.png',
  },
  belt12: {
    id:     'belt12',
    name:   'Belt XII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt12.png',
  },
  belt13: {
    id:     'belt13',
    name:   'Belt XIII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt13.png',
  },
  belt14: {
    id:     'belt14',
    name:   'Belt XIV',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt14.png',
  },
  belt15: {
    id:     'belt15',
    name:   'Belt XV',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt15.png',
  },
  belt16: {
    id:     'belt16',
    name:   'Belt XVI',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt16.png',
  },
  belt17: {
    id:     'belt17',
    name:   'Belt XVII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt17.png',
  },
  belt18: {
    id:     'belt18',
    name:   'Belt XVIII',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt18.png',
  },
  belt19: {
    id:     'belt19',
    name:   'Belt XIX',
    slot:   'belt',
    rarity: 'grey',
    icon:   'assets/items/armor/belt19.png',
  },

  necklace1: {
    id:     'necklace1',
    name:   'Necklace',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace1.png',
  },
  necklace2: {
    id:     'necklace2',
    name:   'Necklace II',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace2.png',
  },
  necklace3: {
    id:     'necklace3',
    name:   'Necklace III',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace3.png',
  },
  necklace4: {
    id:     'necklace4',
    name:   'Necklace IV',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace4.png',
  },
  necklace5: {
    id:     'necklace5',
    name:   'Necklace V',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace5.png',
  },
  necklace6: {
    id:     'necklace6',
    name:   'Necklace VI',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace6.png',
  },
  necklace7: {
    id:     'necklace7',
    name:   'Necklace VII',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace7.png',
  },
  necklace8: {
    id:     'necklace8',
    name:   'Necklace VIII',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace8.png',
  },
  necklace9: {
    id:     'necklace9',
    name:   'Necklace IX',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace9.png',
  },
  necklace10: {
    id:     'necklace10',
    name:   'Necklace X',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace10.png',
  },
  necklace11: {
    id:     'necklace11',
    name:   'Necklace XI',
    slot:   'neck',
    rarity: 'grey',
    icon:   'assets/items/jewelry/necklace11.png',
  },

  robe1: {
    id:     'robe1',
    name:   'Robe',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe1.png',
  },
  robe2: {
    id:     'robe2',
    name:   'Robe II',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe2.png',
  },
  robe3: {
    id:     'robe3',
    name:   'Robe III',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe3.png',
  },
  robe4: {
    id:     'robe4',
    name:   'Robe IV',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe4.png',
  },
  robe5: {
    id:     'robe5',
    name:   'Robe V',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe5.png',
  },
  robe6: {
    id:     'robe6',
    name:   'Robe VI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe6.png',
  },
  robe7: {
    id:     'robe7',
    name:   'Robe VII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe7.png',
  },
  robe8: {
    id:     'robe8',
    name:   'Robe VIII',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe8.png',
  },
  robe9: {
    id:     'robe9',
    name:   'Robe IX',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe9.png',
  },
  robe10: {
    id:     'robe10',
    name:   'Robe X',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe10.png',
  },
  robe11: {
    id:     'robe11',
    name:   'Robe XI',
    slot:   'chest',
    rarity: 'grey',
    icon:   'assets/items/armor/robe11.png',
  },

  glvoes1: {
    id:     'glvoes1',
    name:   'Gloves',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/glvoes1.png',
  },
  gloves2: {
    id:     'gloves2',
    name:   'Gloves II',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/gloves2.png',
  },
  gloves3: {
    id:     'gloves3',
    name:   'Gloves III',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/gloves3.png',
  },
  gloves4: {
    id:     'gloves4',
    name:   'Gloves IV',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/gloves4.png',
  },
  gloves5: {
    id:     'gloves5',
    name:   'Gloves V',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/gloves5.png',
  },
  gloves6: {
    id:     'gloves6',
    name:   'Gloves VI',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/gloves6.png',
  },
  gloves7: {
    id:     'gloves7',
    name:   'Gloves VII',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/gloves7.png',
  },
  gloves8: {
    id:     'gloves8',
    name:   'Gloves VIII',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/gloves8.png',
  },
  gloves9: {
    id:     'gloves9',
    name:   'Gloves IX',
    slot:   'hands',
    rarity: 'grey',
    icon:   'assets/items/armor/gloves9.png',
  },

  wrist1: {
    id:     'wrist1',
    name:   'Bracer',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist1.png',
  },
  wrist2: {
    id:     'wrist2',
    name:   'Bracer II',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist2.png',
  },
  wrist3: {
    id:     'wrist3',
    name:   'Bracer III',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist3.png',
  },
  wrist4: {
    id:     'wrist4',
    name:   'Bracer IV',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist4.png',
  },
  wrist5: {
    id:     'wrist5',
    name:   'Bracer V',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist5.png',
  },
  wrist6: {
    id:     'wrist6',
    name:   'Bracer VI',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist6.png',
  },
  wrist7: {
    id:     'wrist7',
    name:   'Bracer VII',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist7.png',
  },
  wrist8: {
    id:     'wrist8',
    name:   'Bracer VIII',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist8.png',
  },
  wrist9: {
    id:     'wrist9',
    name:   'Bracer IX',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist9.png',
  },
  wrist10: {
    id:     'wrist10',
    name:   'Bracer X',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist10.png',
  },
  wrist11: {
    id:     'wrist11',
    name:   'Bracer XI',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist11.png',
  },
  wrist12: {
    id:     'wrist12',
    name:   'Bracer XII',
    slot:   'wrist',
    rarity: 'grey',
    icon:   'assets/items/armor/wrist12.png',
  },

  ring1: {
    id:     'ring1',
    name:   'Ring',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring1.png',
  },
  ring2: {
    id:     'ring2',
    name:   'Ring II',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring2.png',
  },
  ring3: {
    id:     'ring3',
    name:   'Ring III',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring3.png',
  },
  ring4: {
    id:     'ring4',
    name:   'Ring IV',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring4.png',
  },
  ring5: {
    id:     'ring5',
    name:   'Ring V',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring5.png',
  },
  ring6: {
    id:     'ring6',
    name:   'Ring VI',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring6.png',
  },
  ring7: {
    id:     'ring7',
    name:   'Ring VII',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring7.png',
  },
  ring8: {
    id:     'ring8',
    name:   'Ring VIII',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring8.png',
  },
  ring9: {
    id:     'ring9',
    name:   'Ring IX',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring9.png',
  },
  ring10: {
    id:     'ring10',
    name:   'Ring X',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring10.png',
  },
  ring11: {
    id:     'ring11',
    name:   'Ring XI',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring11.png',
  },
  ring12: {
    id:     'ring12',
    name:   'Ring XII',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring12.png',
  },
  ring13: {
    id:     'ring13',
    name:   'Ring XIII',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring13.png',
  },
  ring14: {
    id:     'ring14',
    name:   'Ring XIV',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring14.png',
  },
  ring15: {
    id:     'ring15',
    name:   'Ring XV',
    slot:   'ring',
    rarity: 'grey',
    icon:   'assets/items/jewelry/ring15.png',
  },
};

export function getItem(id) {
  const def = ITEMS[id];
  return def ? { ...def } : null;
}
